// Code generated by go-swagger; DO NOT EDIT.

package provisioned_devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIWebServiceListProvisionedDevicesReader is a Reader for the ThinkteluControlAPIWebServiceListProvisionedDevices structure.
type ThinkteluControlAPIWebServiceListProvisionedDevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIWebServiceListProvisionedDevicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIWebServiceListProvisionedDevicesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIWebServiceListProvisionedDevicesOK creates a ThinktelUControlAPIWebServiceListProvisionedDevicesOK with default headers values
func NewThinktelUControlAPIWebServiceListProvisionedDevicesOK() *ThinktelUControlAPIWebServiceListProvisionedDevicesOK {
	return &ThinktelUControlAPIWebServiceListProvisionedDevicesOK{}
}

/*
ThinktelUControlAPIWebServiceListProvisionedDevicesOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIWebServiceListProvisionedDevicesOK struct {
	Payload []*models.ThinkteluControlAPIDataContractsProvisionedDevice
}

// IsSuccess returns true when this thinktel u control Api web service list provisioned devices o k response has a 2xx status code
func (o *ThinktelUControlAPIWebServiceListProvisionedDevicesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api web service list provisioned devices o k response has a 3xx status code
func (o *ThinktelUControlAPIWebServiceListProvisionedDevicesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api web service list provisioned devices o k response has a 4xx status code
func (o *ThinktelUControlAPIWebServiceListProvisionedDevicesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api web service list provisioned devices o k response has a 5xx status code
func (o *ThinktelUControlAPIWebServiceListProvisionedDevicesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api web service list provisioned devices o k response a status code equal to that given
func (o *ThinktelUControlAPIWebServiceListProvisionedDevicesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api web service list provisioned devices o k response
func (o *ThinktelUControlAPIWebServiceListProvisionedDevicesOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIWebServiceListProvisionedDevicesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ProvisionedDevices][%d] thinktelUControlApiWebServiceListProvisionedDevicesOK %s", 200, payload)
}

func (o *ThinktelUControlAPIWebServiceListProvisionedDevicesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ProvisionedDevices][%d] thinktelUControlApiWebServiceListProvisionedDevicesOK %s", 200, payload)
}

func (o *ThinktelUControlAPIWebServiceListProvisionedDevicesOK) GetPayload() []*models.ThinkteluControlAPIDataContractsProvisionedDevice {
	return o.Payload
}

func (o *ThinktelUControlAPIWebServiceListProvisionedDevicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIWebServiceListProvisionedDevicesDefault creates a ThinkteluControlAPIWebServiceListProvisionedDevicesDefault with default headers values
func NewThinkteluControlAPIWebServiceListProvisionedDevicesDefault(code int) *ThinkteluControlAPIWebServiceListProvisionedDevicesDefault {
	return &ThinkteluControlAPIWebServiceListProvisionedDevicesDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIWebServiceListProvisionedDevicesDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIWebServiceListProvisionedDevicesDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api web service list provisioned devices default response has a 2xx status code
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api web service list provisioned devices default response has a 3xx status code
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api web service list provisioned devices default response has a 4xx status code
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api web service list provisioned devices default response has a 5xx status code
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api web service list provisioned devices default response a status code equal to that given
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api web service list provisioned devices default response
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ProvisionedDevices][%d] Thinktel.uControl.Api.WebService.ListProvisionedDevices default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ProvisionedDevices][%d] Thinktel.uControl.Api.WebService.ListProvisionedDevices default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
