// Code generated by go-swagger; DO NOT EDIT.

package provisioned_devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIRestServiceUpdateProvisionedDeviceReader is a Reader for the ThinkteluControlAPIRestServiceUpdateProvisionedDevice structure.
type ThinkteluControlAPIRestServiceUpdateProvisionedDeviceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIRestServiceUpdateProvisionedDeviceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK creates a ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK with default headers values
func NewThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK() *ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK {
	return &ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK{}
}

/*
ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK struct {
	Payload *models.ThinkteluControlAPIDataContractsNameResponse
}

// IsSuccess returns true when this thinktel u control Api rest service update provisioned device o k response has a 2xx status code
func (o *ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api rest service update provisioned device o k response has a 3xx status code
func (o *ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api rest service update provisioned device o k response has a 4xx status code
func (o *ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api rest service update provisioned device o k response has a 5xx status code
func (o *ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api rest service update provisioned device o k response a status code equal to that given
func (o *ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api rest service update provisioned device o k response
func (o *ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /ProvisionedDevices/{MACAddress}][%d] thinktelUControlApiRestServiceUpdateProvisionedDeviceOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /ProvisionedDevices/{MACAddress}][%d] thinktelUControlApiRestServiceUpdateProvisionedDeviceOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK) GetPayload() *models.ThinkteluControlAPIDataContractsNameResponse {
	return o.Payload
}

func (o *ThinktelUControlAPIRestServiceUpdateProvisionedDeviceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsNameResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault creates a ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault with default headers values
func NewThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault(code int) *ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault {
	return &ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api rest service update provisioned device default response has a 2xx status code
func (o *ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api rest service update provisioned device default response has a 3xx status code
func (o *ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api rest service update provisioned device default response has a 4xx status code
func (o *ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api rest service update provisioned device default response has a 5xx status code
func (o *ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api rest service update provisioned device default response a status code equal to that given
func (o *ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api rest service update provisioned device default response
func (o *ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /ProvisionedDevices/{MACAddress}][%d] Thinktel.uControl.Api.RestService.UpdateProvisionedDevice default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /ProvisionedDevices/{MACAddress}][%d] Thinktel.uControl.Api.RestService.UpdateProvisionedDevice default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIRestServiceUpdateProvisionedDeviceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
