// Code generated by go-swagger; DO NOT EDIT.

package provisioned_devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewThinkteluControlAPIWebServiceListProvisionedDevicesParams creates a new ThinkteluControlAPIWebServiceListProvisionedDevicesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIWebServiceListProvisionedDevicesParams() *ThinkteluControlAPIWebServiceListProvisionedDevicesParams {
	return &ThinkteluControlAPIWebServiceListProvisionedDevicesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIWebServiceListProvisionedDevicesParamsWithTimeout creates a new ThinkteluControlAPIWebServiceListProvisionedDevicesParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIWebServiceListProvisionedDevicesParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceListProvisionedDevicesParams {
	return &ThinkteluControlAPIWebServiceListProvisionedDevicesParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIWebServiceListProvisionedDevicesParamsWithContext creates a new ThinkteluControlAPIWebServiceListProvisionedDevicesParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIWebServiceListProvisionedDevicesParamsWithContext(ctx context.Context) *ThinkteluControlAPIWebServiceListProvisionedDevicesParams {
	return &ThinkteluControlAPIWebServiceListProvisionedDevicesParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIWebServiceListProvisionedDevicesParamsWithHTTPClient creates a new ThinkteluControlAPIWebServiceListProvisionedDevicesParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIWebServiceListProvisionedDevicesParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceListProvisionedDevicesParams {
	return &ThinkteluControlAPIWebServiceListProvisionedDevicesParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIWebServiceListProvisionedDevicesParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api web service list provisioned devices operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIWebServiceListProvisionedDevicesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api web service list provisioned devices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesParams) WithDefaults() *ThinkteluControlAPIWebServiceListProvisionedDevicesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api web service list provisioned devices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api web service list provisioned devices params
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceListProvisionedDevicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api web service list provisioned devices params
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api web service list provisioned devices params
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesParams) WithContext(ctx context.Context) *ThinkteluControlAPIWebServiceListProvisionedDevicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api web service list provisioned devices params
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api web service list provisioned devices params
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceListProvisionedDevicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api web service list provisioned devices params
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIWebServiceListProvisionedDevicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
