// Code generated by go-swagger; DO NOT EDIT.

package business_lines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIRestServiceCancelBusinessLineReader is a Reader for the ThinkteluControlAPIRestServiceCancelBusinessLine structure.
type ThinkteluControlAPIRestServiceCancelBusinessLineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIRestServiceCancelBusinessLineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIRestServiceCancelBusinessLineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIRestServiceCancelBusinessLineDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIRestServiceCancelBusinessLineOK creates a ThinktelUControlAPIRestServiceCancelBusinessLineOK with default headers values
func NewThinktelUControlAPIRestServiceCancelBusinessLineOK() *ThinktelUControlAPIRestServiceCancelBusinessLineOK {
	return &ThinktelUControlAPIRestServiceCancelBusinessLineOK{}
}

/*
ThinktelUControlAPIRestServiceCancelBusinessLineOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIRestServiceCancelBusinessLineOK struct {
	Payload *models.ThinkteluControlAPIDataContractsNumberResponse
}

// IsSuccess returns true when this thinktel u control Api rest service cancel business line o k response has a 2xx status code
func (o *ThinktelUControlAPIRestServiceCancelBusinessLineOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api rest service cancel business line o k response has a 3xx status code
func (o *ThinktelUControlAPIRestServiceCancelBusinessLineOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api rest service cancel business line o k response has a 4xx status code
func (o *ThinktelUControlAPIRestServiceCancelBusinessLineOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api rest service cancel business line o k response has a 5xx status code
func (o *ThinktelUControlAPIRestServiceCancelBusinessLineOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api rest service cancel business line o k response a status code equal to that given
func (o *ThinktelUControlAPIRestServiceCancelBusinessLineOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api rest service cancel business line o k response
func (o *ThinktelUControlAPIRestServiceCancelBusinessLineOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIRestServiceCancelBusinessLineOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /BusinessLines/{number}][%d] thinktelUControlApiRestServiceCancelBusinessLineOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceCancelBusinessLineOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /BusinessLines/{number}][%d] thinktelUControlApiRestServiceCancelBusinessLineOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceCancelBusinessLineOK) GetPayload() *models.ThinkteluControlAPIDataContractsNumberResponse {
	return o.Payload
}

func (o *ThinktelUControlAPIRestServiceCancelBusinessLineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsNumberResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIRestServiceCancelBusinessLineDefault creates a ThinkteluControlAPIRestServiceCancelBusinessLineDefault with default headers values
func NewThinkteluControlAPIRestServiceCancelBusinessLineDefault(code int) *ThinkteluControlAPIRestServiceCancelBusinessLineDefault {
	return &ThinkteluControlAPIRestServiceCancelBusinessLineDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIRestServiceCancelBusinessLineDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIRestServiceCancelBusinessLineDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api rest service cancel business line default response has a 2xx status code
func (o *ThinkteluControlAPIRestServiceCancelBusinessLineDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api rest service cancel business line default response has a 3xx status code
func (o *ThinkteluControlAPIRestServiceCancelBusinessLineDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api rest service cancel business line default response has a 4xx status code
func (o *ThinkteluControlAPIRestServiceCancelBusinessLineDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api rest service cancel business line default response has a 5xx status code
func (o *ThinkteluControlAPIRestServiceCancelBusinessLineDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api rest service cancel business line default response a status code equal to that given
func (o *ThinkteluControlAPIRestServiceCancelBusinessLineDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api rest service cancel business line default response
func (o *ThinkteluControlAPIRestServiceCancelBusinessLineDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIRestServiceCancelBusinessLineDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /BusinessLines/{number}][%d] Thinktel.uControl.Api.RestService.CancelBusinessLine default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceCancelBusinessLineDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /BusinessLines/{number}][%d] Thinktel.uControl.Api.RestService.CancelBusinessLine default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceCancelBusinessLineDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIRestServiceCancelBusinessLineDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
