// Code generated by go-swagger; DO NOT EDIT.

package business_lines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// NewThinkteluControlAPIWebServiceAddBusinessLineParams creates a new ThinkteluControlAPIWebServiceAddBusinessLineParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIWebServiceAddBusinessLineParams() *ThinkteluControlAPIWebServiceAddBusinessLineParams {
	return &ThinkteluControlAPIWebServiceAddBusinessLineParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIWebServiceAddBusinessLineParamsWithTimeout creates a new ThinkteluControlAPIWebServiceAddBusinessLineParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIWebServiceAddBusinessLineParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceAddBusinessLineParams {
	return &ThinkteluControlAPIWebServiceAddBusinessLineParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIWebServiceAddBusinessLineParamsWithContext creates a new ThinkteluControlAPIWebServiceAddBusinessLineParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIWebServiceAddBusinessLineParamsWithContext(ctx context.Context) *ThinkteluControlAPIWebServiceAddBusinessLineParams {
	return &ThinkteluControlAPIWebServiceAddBusinessLineParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIWebServiceAddBusinessLineParamsWithHTTPClient creates a new ThinkteluControlAPIWebServiceAddBusinessLineParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIWebServiceAddBusinessLineParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceAddBusinessLineParams {
	return &ThinkteluControlAPIWebServiceAddBusinessLineParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIWebServiceAddBusinessLineParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api web service add business line operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIWebServiceAddBusinessLineParams struct {

	/* Order.

	   Business line order.
	*/
	Order *models.ThinkteluControlAPIDataContractsBusinessLineOrder

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api web service add business line params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceAddBusinessLineParams) WithDefaults() *ThinkteluControlAPIWebServiceAddBusinessLineParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api web service add business line params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceAddBusinessLineParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api web service add business line params
func (o *ThinkteluControlAPIWebServiceAddBusinessLineParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceAddBusinessLineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api web service add business line params
func (o *ThinkteluControlAPIWebServiceAddBusinessLineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api web service add business line params
func (o *ThinkteluControlAPIWebServiceAddBusinessLineParams) WithContext(ctx context.Context) *ThinkteluControlAPIWebServiceAddBusinessLineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api web service add business line params
func (o *ThinkteluControlAPIWebServiceAddBusinessLineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api web service add business line params
func (o *ThinkteluControlAPIWebServiceAddBusinessLineParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceAddBusinessLineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api web service add business line params
func (o *ThinkteluControlAPIWebServiceAddBusinessLineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrder adds the order to the thinktel u control Api web service add business line params
func (o *ThinkteluControlAPIWebServiceAddBusinessLineParams) WithOrder(order *models.ThinkteluControlAPIDataContractsBusinessLineOrder) *ThinkteluControlAPIWebServiceAddBusinessLineParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the thinktel u control Api web service add business line params
func (o *ThinkteluControlAPIWebServiceAddBusinessLineParams) SetOrder(order *models.ThinkteluControlAPIDataContractsBusinessLineOrder) {
	o.Order = order
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIWebServiceAddBusinessLineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Order != nil {
		if err := r.SetBodyParam(o.Order); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
