// Code generated by go-swagger; DO NOT EDIT.

package rate_centers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewThinkteluControlAPIWebServiceListRateCenterNext10Params creates a new ThinkteluControlAPIWebServiceListRateCenterNext10Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIWebServiceListRateCenterNext10Params() *ThinkteluControlAPIWebServiceListRateCenterNext10Params {
	return &ThinkteluControlAPIWebServiceListRateCenterNext10Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIWebServiceListRateCenterNext10ParamsWithTimeout creates a new ThinkteluControlAPIWebServiceListRateCenterNext10Params object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIWebServiceListRateCenterNext10ParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceListRateCenterNext10Params {
	return &ThinkteluControlAPIWebServiceListRateCenterNext10Params{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIWebServiceListRateCenterNext10ParamsWithContext creates a new ThinkteluControlAPIWebServiceListRateCenterNext10Params object
// with the ability to set a context for a request.
func NewThinkteluControlAPIWebServiceListRateCenterNext10ParamsWithContext(ctx context.Context) *ThinkteluControlAPIWebServiceListRateCenterNext10Params {
	return &ThinkteluControlAPIWebServiceListRateCenterNext10Params{
		Context: ctx,
	}
}

// NewThinkteluControlAPIWebServiceListRateCenterNext10ParamsWithHTTPClient creates a new ThinkteluControlAPIWebServiceListRateCenterNext10Params object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIWebServiceListRateCenterNext10ParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceListRateCenterNext10Params {
	return &ThinkteluControlAPIWebServiceListRateCenterNext10Params{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIWebServiceListRateCenterNext10Params contains all the parameters to send to the API endpoint

	for the thinktel u control Api web service list rate center next10 operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIWebServiceListRateCenterNext10Params struct {

	/* Name.

	   Rate center name.
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api web service list rate center next10 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceListRateCenterNext10Params) WithDefaults() *ThinkteluControlAPIWebServiceListRateCenterNext10Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api web service list rate center next10 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceListRateCenterNext10Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api web service list rate center next10 params
func (o *ThinkteluControlAPIWebServiceListRateCenterNext10Params) WithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceListRateCenterNext10Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api web service list rate center next10 params
func (o *ThinkteluControlAPIWebServiceListRateCenterNext10Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api web service list rate center next10 params
func (o *ThinkteluControlAPIWebServiceListRateCenterNext10Params) WithContext(ctx context.Context) *ThinkteluControlAPIWebServiceListRateCenterNext10Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api web service list rate center next10 params
func (o *ThinkteluControlAPIWebServiceListRateCenterNext10Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api web service list rate center next10 params
func (o *ThinkteluControlAPIWebServiceListRateCenterNext10Params) WithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceListRateCenterNext10Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api web service list rate center next10 params
func (o *ThinkteluControlAPIWebServiceListRateCenterNext10Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the thinktel u control Api web service list rate center next10 params
func (o *ThinkteluControlAPIWebServiceListRateCenterNext10Params) WithName(name string) *ThinkteluControlAPIWebServiceListRateCenterNext10Params {
	o.SetName(name)
	return o
}

// SetName adds the name to the thinktel u control Api web service list rate center next10 params
func (o *ThinkteluControlAPIWebServiceListRateCenterNext10Params) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIWebServiceListRateCenterNext10Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
