// Code generated by go-swagger; DO NOT EDIT.

package rate_centers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams creates a new ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams() *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams {
	return &ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIWebServiceListCountryProvinceRateCentersParamsWithTimeout creates a new ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIWebServiceListCountryProvinceRateCentersParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams {
	return &ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIWebServiceListCountryProvinceRateCentersParamsWithContext creates a new ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIWebServiceListCountryProvinceRateCentersParamsWithContext(ctx context.Context) *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams {
	return &ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIWebServiceListCountryProvinceRateCentersParamsWithHTTPClient creates a new ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIWebServiceListCountryProvinceRateCentersParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams {
	return &ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api web service list country province rate centers operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams struct {

	/* CountryAlpha2.

	   Country code (ISO-3166-1 Alpha2 Code).
	*/
	CountryAlpha2 string

	/* ProvinceAlpha2.

	   Country subdivision code (ISO-3166-2 Alpha2 Code).
	*/
	ProvinceAlpha2 string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api web service list country province rate centers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams) WithDefaults() *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api web service list country province rate centers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api web service list country province rate centers params
func (o *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api web service list country province rate centers params
func (o *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api web service list country province rate centers params
func (o *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams) WithContext(ctx context.Context) *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api web service list country province rate centers params
func (o *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api web service list country province rate centers params
func (o *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api web service list country province rate centers params
func (o *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCountryAlpha2 adds the countryAlpha2 to the thinktel u control Api web service list country province rate centers params
func (o *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams) WithCountryAlpha2(countryAlpha2 string) *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams {
	o.SetCountryAlpha2(countryAlpha2)
	return o
}

// SetCountryAlpha2 adds the countryAlpha2 to the thinktel u control Api web service list country province rate centers params
func (o *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams) SetCountryAlpha2(countryAlpha2 string) {
	o.CountryAlpha2 = countryAlpha2
}

// WithProvinceAlpha2 adds the provinceAlpha2 to the thinktel u control Api web service list country province rate centers params
func (o *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams) WithProvinceAlpha2(provinceAlpha2 string) *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams {
	o.SetProvinceAlpha2(provinceAlpha2)
	return o
}

// SetProvinceAlpha2 adds the provinceAlpha2 to the thinktel u control Api web service list country province rate centers params
func (o *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams) SetProvinceAlpha2(provinceAlpha2 string) {
	o.ProvinceAlpha2 = provinceAlpha2
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIWebServiceListCountryProvinceRateCentersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param country_alpha_2
	if err := r.SetPathParam("country_alpha_2", o.CountryAlpha2); err != nil {
		return err
	}

	// path param province_alpha_2
	if err := r.SetPathParam("province_alpha_2", o.ProvinceAlpha2); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
