// Code generated by go-swagger; DO NOT EDIT.

package rate_centers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIWebServiceListCountryRateCentersReader is a Reader for the ThinkteluControlAPIWebServiceListCountryRateCenters structure.
type ThinkteluControlAPIWebServiceListCountryRateCentersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIWebServiceListCountryRateCentersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIWebServiceListCountryRateCentersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIWebServiceListCountryRateCentersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIWebServiceListCountryRateCentersOK creates a ThinktelUControlAPIWebServiceListCountryRateCentersOK with default headers values
func NewThinktelUControlAPIWebServiceListCountryRateCentersOK() *ThinktelUControlAPIWebServiceListCountryRateCentersOK {
	return &ThinktelUControlAPIWebServiceListCountryRateCentersOK{}
}

/*
ThinktelUControlAPIWebServiceListCountryRateCentersOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIWebServiceListCountryRateCentersOK struct {
	Payload []*models.ThinkteluControlAPIDataContractsTerseRateCenter
}

// IsSuccess returns true when this thinktel u control Api web service list country rate centers o k response has a 2xx status code
func (o *ThinktelUControlAPIWebServiceListCountryRateCentersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api web service list country rate centers o k response has a 3xx status code
func (o *ThinktelUControlAPIWebServiceListCountryRateCentersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api web service list country rate centers o k response has a 4xx status code
func (o *ThinktelUControlAPIWebServiceListCountryRateCentersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api web service list country rate centers o k response has a 5xx status code
func (o *ThinktelUControlAPIWebServiceListCountryRateCentersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api web service list country rate centers o k response a status code equal to that given
func (o *ThinktelUControlAPIWebServiceListCountryRateCentersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api web service list country rate centers o k response
func (o *ThinktelUControlAPIWebServiceListCountryRateCentersOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIWebServiceListCountryRateCentersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /RateCenters/Country/{country_alpha_2}][%d] thinktelUControlApiWebServiceListCountryRateCentersOK %s", 200, payload)
}

func (o *ThinktelUControlAPIWebServiceListCountryRateCentersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /RateCenters/Country/{country_alpha_2}][%d] thinktelUControlApiWebServiceListCountryRateCentersOK %s", 200, payload)
}

func (o *ThinktelUControlAPIWebServiceListCountryRateCentersOK) GetPayload() []*models.ThinkteluControlAPIDataContractsTerseRateCenter {
	return o.Payload
}

func (o *ThinktelUControlAPIWebServiceListCountryRateCentersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIWebServiceListCountryRateCentersDefault creates a ThinkteluControlAPIWebServiceListCountryRateCentersDefault with default headers values
func NewThinkteluControlAPIWebServiceListCountryRateCentersDefault(code int) *ThinkteluControlAPIWebServiceListCountryRateCentersDefault {
	return &ThinkteluControlAPIWebServiceListCountryRateCentersDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIWebServiceListCountryRateCentersDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIWebServiceListCountryRateCentersDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api web service list country rate centers default response has a 2xx status code
func (o *ThinkteluControlAPIWebServiceListCountryRateCentersDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api web service list country rate centers default response has a 3xx status code
func (o *ThinkteluControlAPIWebServiceListCountryRateCentersDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api web service list country rate centers default response has a 4xx status code
func (o *ThinkteluControlAPIWebServiceListCountryRateCentersDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api web service list country rate centers default response has a 5xx status code
func (o *ThinkteluControlAPIWebServiceListCountryRateCentersDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api web service list country rate centers default response a status code equal to that given
func (o *ThinkteluControlAPIWebServiceListCountryRateCentersDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api web service list country rate centers default response
func (o *ThinkteluControlAPIWebServiceListCountryRateCentersDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIWebServiceListCountryRateCentersDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /RateCenters/Country/{country_alpha_2}][%d] Thinktel.uControl.Api.WebService.ListCountryRateCenters default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIWebServiceListCountryRateCentersDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /RateCenters/Country/{country_alpha_2}][%d] Thinktel.uControl.Api.WebService.ListCountryRateCenters default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIWebServiceListCountryRateCentersDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIWebServiceListCountryRateCentersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
