// Code generated by go-swagger; DO NOT EDIT.

package deprecated

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// NewThinkteluControlAPIWebServiceAddNumberPortDIDParams creates a new ThinkteluControlAPIWebServiceAddNumberPortDIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIWebServiceAddNumberPortDIDParams() *ThinkteluControlAPIWebServiceAddNumberPortDIDParams {
	return &ThinkteluControlAPIWebServiceAddNumberPortDIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIWebServiceAddNumberPortDIDParamsWithTimeout creates a new ThinkteluControlAPIWebServiceAddNumberPortDIDParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIWebServiceAddNumberPortDIDParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceAddNumberPortDIDParams {
	return &ThinkteluControlAPIWebServiceAddNumberPortDIDParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIWebServiceAddNumberPortDIDParamsWithContext creates a new ThinkteluControlAPIWebServiceAddNumberPortDIDParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIWebServiceAddNumberPortDIDParamsWithContext(ctx context.Context) *ThinkteluControlAPIWebServiceAddNumberPortDIDParams {
	return &ThinkteluControlAPIWebServiceAddNumberPortDIDParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIWebServiceAddNumberPortDIDParamsWithHTTPClient creates a new ThinkteluControlAPIWebServiceAddNumberPortDIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIWebServiceAddNumberPortDIDParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceAddNumberPortDIDParams {
	return &ThinkteluControlAPIWebServiceAddNumberPortDIDParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIWebServiceAddNumberPortDIDParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api web service add number port DID operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIWebServiceAddNumberPortDIDParams struct {

	/* OrderForm.

	   SIP trunk DID port-in order.
	*/
	OrderForm *models.ThinkteluControlAPIDataContractsNumberPortOrderDID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api web service add number port DID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceAddNumberPortDIDParams) WithDefaults() *ThinkteluControlAPIWebServiceAddNumberPortDIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api web service add number port DID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceAddNumberPortDIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api web service add number port DID params
func (o *ThinkteluControlAPIWebServiceAddNumberPortDIDParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceAddNumberPortDIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api web service add number port DID params
func (o *ThinkteluControlAPIWebServiceAddNumberPortDIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api web service add number port DID params
func (o *ThinkteluControlAPIWebServiceAddNumberPortDIDParams) WithContext(ctx context.Context) *ThinkteluControlAPIWebServiceAddNumberPortDIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api web service add number port DID params
func (o *ThinkteluControlAPIWebServiceAddNumberPortDIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api web service add number port DID params
func (o *ThinkteluControlAPIWebServiceAddNumberPortDIDParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceAddNumberPortDIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api web service add number port DID params
func (o *ThinkteluControlAPIWebServiceAddNumberPortDIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderForm adds the orderForm to the thinktel u control Api web service add number port DID params
func (o *ThinkteluControlAPIWebServiceAddNumberPortDIDParams) WithOrderForm(orderForm *models.ThinkteluControlAPIDataContractsNumberPortOrderDID) *ThinkteluControlAPIWebServiceAddNumberPortDIDParams {
	o.SetOrderForm(orderForm)
	return o
}

// SetOrderForm adds the orderForm to the thinktel u control Api web service add number port DID params
func (o *ThinkteluControlAPIWebServiceAddNumberPortDIDParams) SetOrderForm(orderForm *models.ThinkteluControlAPIDataContractsNumberPortOrderDID) {
	o.OrderForm = orderForm
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIWebServiceAddNumberPortDIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.OrderForm != nil {
		if err := r.SetBodyParam(o.OrderForm); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
