// Code generated by go-swagger; DO NOT EDIT.

package deprecated

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewThinkteluControlAPIWebServiceListV911sv2DeprecatedParams creates a new ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIWebServiceListV911sv2DeprecatedParams() *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams {
	return &ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIWebServiceListV911sv2DeprecatedParamsWithTimeout creates a new ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIWebServiceListV911sv2DeprecatedParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams {
	return &ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIWebServiceListV911sv2DeprecatedParamsWithContext creates a new ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIWebServiceListV911sv2DeprecatedParamsWithContext(ctx context.Context) *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams {
	return &ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIWebServiceListV911sv2DeprecatedParamsWithHTTPClient creates a new ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIWebServiceListV911sv2DeprecatedParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams {
	return &ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api web service list v911sv2 deprecated operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api web service list v911sv2 deprecated params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams) WithDefaults() *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api web service list v911sv2 deprecated params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api web service list v911sv2 deprecated params
func (o *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api web service list v911sv2 deprecated params
func (o *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api web service list v911sv2 deprecated params
func (o *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams) WithContext(ctx context.Context) *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api web service list v911sv2 deprecated params
func (o *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api web service list v911sv2 deprecated params
func (o *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api web service list v911sv2 deprecated params
func (o *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIWebServiceListV911sv2DeprecatedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
