// Code generated by go-swagger; DO NOT EDIT.

package deprecated

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedReader is a Reader for the ThinkteluControlAPIRestServiceUpdateV911v2Deprecated structure.
type ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK creates a ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK with default headers values
func NewThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK() *ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK {
	return &ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK{}
}

/*
ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK struct {
	Payload *models.ThinkteluControlAPIDataContractsV911Response
}

// IsSuccess returns true when this thinktel u control Api rest service update v911v2 deprecated o k response has a 2xx status code
func (o *ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api rest service update v911v2 deprecated o k response has a 3xx status code
func (o *ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api rest service update v911v2 deprecated o k response has a 4xx status code
func (o *ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api rest service update v911v2 deprecated o k response has a 5xx status code
func (o *ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api rest service update v911v2 deprecated o k response a status code equal to that given
func (o *ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api rest service update v911v2 deprecated o k response
func (o *ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /V911s/v2/{number}][%d] thinktelUControlApiRestServiceUpdateV911v2DeprecatedOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /V911s/v2/{number}][%d] thinktelUControlApiRestServiceUpdateV911v2DeprecatedOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK) GetPayload() *models.ThinkteluControlAPIDataContractsV911Response {
	return o.Payload
}

func (o *ThinktelUControlAPIRestServiceUpdateV911v2DeprecatedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsV911Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault creates a ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault with default headers values
func NewThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault(code int) *ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault {
	return &ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api rest service update v911v2 deprecated default response has a 2xx status code
func (o *ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api rest service update v911v2 deprecated default response has a 3xx status code
func (o *ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api rest service update v911v2 deprecated default response has a 4xx status code
func (o *ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api rest service update v911v2 deprecated default response has a 5xx status code
func (o *ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api rest service update v911v2 deprecated default response a status code equal to that given
func (o *ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api rest service update v911v2 deprecated default response
func (o *ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /V911s/v2/{number}][%d] Thinktel.uControl.Api.RestService.UpdateV911v2_Deprecated default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /V911s/v2/{number}][%d] Thinktel.uControl.Api.RestService.UpdateV911v2_Deprecated default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIRestServiceUpdateV911v2DeprecatedDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
