// Code generated by go-swagger; DO NOT EDIT.

package deprecated

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedReader is a Reader for the ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecated structure.
type ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK creates a ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK with default headers values
func NewThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK() *ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK {
	return &ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK{}
}

/*
ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK struct {
	Payload *models.ThinkteluControlAPIDataContractsNumberResponse
}

// IsSuccess returns true when this thinktel u control Api rest service update subscriber premium features deprecated o k response has a 2xx status code
func (o *ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api rest service update subscriber premium features deprecated o k response has a 3xx status code
func (o *ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api rest service update subscriber premium features deprecated o k response has a 4xx status code
func (o *ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api rest service update subscriber premium features deprecated o k response has a 5xx status code
func (o *ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api rest service update subscriber premium features deprecated o k response a status code equal to that given
func (o *ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api rest service update subscriber premium features deprecated o k response
func (o *ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /SipTrunk/{pilot}/PremiumFeatures][%d] thinktelUControlApiRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /SipTrunk/{pilot}/PremiumFeatures][%d] thinktelUControlApiRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK) GetPayload() *models.ThinkteluControlAPIDataContractsNumberResponse {
	return o.Payload
}

func (o *ThinktelUControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsNumberResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault creates a ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault with default headers values
func NewThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault(code int) *ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault {
	return &ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api rest service update subscriber premium features deprecated default response has a 2xx status code
func (o *ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api rest service update subscriber premium features deprecated default response has a 3xx status code
func (o *ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api rest service update subscriber premium features deprecated default response has a 4xx status code
func (o *ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api rest service update subscriber premium features deprecated default response has a 5xx status code
func (o *ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api rest service update subscriber premium features deprecated default response a status code equal to that given
func (o *ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api rest service update subscriber premium features deprecated default response
func (o *ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /SipTrunk/{pilot}/PremiumFeatures][%d] Thinktel.uControl.Api.RestService.UpdateSubscriberPremiumFeatures_Deprecated default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /SipTrunk/{pilot}/PremiumFeatures][%d] Thinktel.uControl.Api.RestService.UpdateSubscriberPremiumFeatures_Deprecated default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIRestServiceUpdateSubscriberPremiumFeaturesDeprecatedDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
