// Code generated by go-swagger; DO NOT EDIT.

package deprecated

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams creates a new ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams() *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams {
	return &ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineParamsWithTimeout creates a new ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams {
	return &ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineParamsWithContext creates a new ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineParamsWithContext(ctx context.Context) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams {
	return &ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineParamsWithHTTPClient creates a new ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams {
	return &ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api web service add number port business line operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams struct {

	/* OrderForm.

	   Business line port-in order.
	*/
	OrderForm *models.ThinkteluControlAPIDataContractsNumberPortOrderBusinessLine

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api web service add number port business line params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams) WithDefaults() *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api web service add number port business line params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api web service add number port business line params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api web service add number port business line params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api web service add number port business line params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams) WithContext(ctx context.Context) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api web service add number port business line params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api web service add number port business line params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api web service add number port business line params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderForm adds the orderForm to the thinktel u control Api web service add number port business line params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams) WithOrderForm(orderForm *models.ThinkteluControlAPIDataContractsNumberPortOrderBusinessLine) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams {
	o.SetOrderForm(orderForm)
	return o
}

// SetOrderForm adds the orderForm to the thinktel u control Api web service add number port business line params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams) SetOrderForm(orderForm *models.ThinkteluControlAPIDataContractsNumberPortOrderBusinessLine) {
	o.OrderForm = orderForm
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.OrderForm != nil {
		if err := r.SetBodyParam(o.OrderForm); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
