// Code generated by go-swagger; DO NOT EDIT.

package deprecated

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// NewThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams creates a new ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams() *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams {
	return &ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParamsWithTimeout creates a new ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams {
	return &ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParamsWithContext creates a new ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParamsWithContext(ctx context.Context) *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams {
	return &ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParamsWithHTTPClient creates a new ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams {
	return &ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api rest service update DID premium features deprecated operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams struct {

	/* Features.

	   Updated DID premium features.
	*/
	Features *models.ThinkteluControlAPIDataContractsDIDSIPTrunkFeatures

	/* Number.

	   DID number.
	*/
	Number string

	/* Pilot.

	   SIP trunk directory number.
	*/
	Pilot string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api rest service update DID premium features deprecated params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) WithDefaults() *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api rest service update DID premium features deprecated params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api rest service update DID premium features deprecated params
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api rest service update DID premium features deprecated params
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api rest service update DID premium features deprecated params
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) WithContext(ctx context.Context) *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api rest service update DID premium features deprecated params
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api rest service update DID premium features deprecated params
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api rest service update DID premium features deprecated params
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFeatures adds the features to the thinktel u control Api rest service update DID premium features deprecated params
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) WithFeatures(features *models.ThinkteluControlAPIDataContractsDIDSIPTrunkFeatures) *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams {
	o.SetFeatures(features)
	return o
}

// SetFeatures adds the features to the thinktel u control Api rest service update DID premium features deprecated params
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) SetFeatures(features *models.ThinkteluControlAPIDataContractsDIDSIPTrunkFeatures) {
	o.Features = features
}

// WithNumber adds the number to the thinktel u control Api rest service update DID premium features deprecated params
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) WithNumber(number string) *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the thinktel u control Api rest service update DID premium features deprecated params
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) SetNumber(number string) {
	o.Number = number
}

// WithPilot adds the pilot to the thinktel u control Api rest service update DID premium features deprecated params
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) WithPilot(pilot string) *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams {
	o.SetPilot(pilot)
	return o
}

// SetPilot adds the pilot to the thinktel u control Api rest service update DID premium features deprecated params
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) SetPilot(pilot string) {
	o.Pilot = pilot
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIRestServiceUpdateDIDPremiumFeaturesDeprecatedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Features != nil {
		if err := r.SetBodyParam(o.Features); err != nil {
			return err
		}
	}

	// path param number
	if err := r.SetPathParam("number", o.Number); err != nil {
		return err
	}

	// path param pilot
	if err := r.SetPathParam("pilot", o.Pilot); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
