// Code generated by go-swagger; DO NOT EDIT.

package tests

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIWebServiceBaseTestExceptionReader is a Reader for the ThinkteluControlAPIWebServiceBaseTestException structure.
type ThinkteluControlAPIWebServiceBaseTestExceptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIWebServiceBaseTestExceptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 500:
		result := NewThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /Test/Exception] Thinktel.uControl.Api.WebServiceBase.TestException", response, response.Code())
	}
}

// NewThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError creates a ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError with default headers values
func NewThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError() *ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError {
	return &ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError{}
}

/*
ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError describes a response with status code 500, with default header values.

Always generates exception
*/
type ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError struct {
	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api web service base test exception internal server error response has a 2xx status code
func (o *ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this thinktel u control Api web service base test exception internal server error response has a 3xx status code
func (o *ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api web service base test exception internal server error response has a 4xx status code
func (o *ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api web service base test exception internal server error response has a 5xx status code
func (o *ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this thinktel u control Api web service base test exception internal server error response a status code equal to that given
func (o *ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the thinktel u control Api web service base test exception internal server error response
func (o *ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError) Code() int {
	return 500
}

func (o *ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Test/Exception][%d] thinktelUControlApiWebServiceBaseTestExceptionInternalServerError %s", 500, payload)
}

func (o *ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Test/Exception][%d] thinktelUControlApiWebServiceBaseTestExceptionInternalServerError %s", 500, payload)
}

func (o *ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinktelUControlAPIWebServiceBaseTestExceptionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
