// Code generated by go-swagger; DO NOT EDIT.

package tests

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams creates a new ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams() *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams {
	return &ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParamsWithTimeout creates a new ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams {
	return &ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParamsWithContext creates a new ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParamsWithContext(ctx context.Context) *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams {
	return &ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParamsWithHTTPClient creates a new ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams {
	return &ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api web service base test not implemented exception operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api web service base test not implemented exception params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams) WithDefaults() *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api web service base test not implemented exception params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api web service base test not implemented exception params
func (o *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api web service base test not implemented exception params
func (o *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api web service base test not implemented exception params
func (o *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams) WithContext(ctx context.Context) *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api web service base test not implemented exception params
func (o *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api web service base test not implemented exception params
func (o *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api web service base test not implemented exception params
func (o *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIWebServiceBaseTestNotImplementedExceptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
