// Code generated by go-swagger; DO NOT EDIT.

package permanent_call_forwards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// NewThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams creates a new ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams() *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams {
	return &ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIRestServiceUpdatePermanentCallForwardParamsWithTimeout creates a new ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIRestServiceUpdatePermanentCallForwardParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams {
	return &ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIRestServiceUpdatePermanentCallForwardParamsWithContext creates a new ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIRestServiceUpdatePermanentCallForwardParamsWithContext(ctx context.Context) *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams {
	return &ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIRestServiceUpdatePermanentCallForwardParamsWithHTTPClient creates a new ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIRestServiceUpdatePermanentCallForwardParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams {
	return &ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api rest service update permanent call forward operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams struct {

	/* Forward.

	   Updated permanent call forward.
	*/
	Forward *models.ThinkteluControlAPIDataContractsPermanentCallForward

	/* Number.

	   Telephone number.
	*/
	Number string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api rest service update permanent call forward params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams) WithDefaults() *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api rest service update permanent call forward params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api rest service update permanent call forward params
func (o *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api rest service update permanent call forward params
func (o *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api rest service update permanent call forward params
func (o *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams) WithContext(ctx context.Context) *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api rest service update permanent call forward params
func (o *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api rest service update permanent call forward params
func (o *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api rest service update permanent call forward params
func (o *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithForward adds the forward to the thinktel u control Api rest service update permanent call forward params
func (o *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams) WithForward(forward *models.ThinkteluControlAPIDataContractsPermanentCallForward) *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams {
	o.SetForward(forward)
	return o
}

// SetForward adds the forward to the thinktel u control Api rest service update permanent call forward params
func (o *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams) SetForward(forward *models.ThinkteluControlAPIDataContractsPermanentCallForward) {
	o.Forward = forward
}

// WithNumber adds the number to the thinktel u control Api rest service update permanent call forward params
func (o *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams) WithNumber(number string) *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the thinktel u control Api rest service update permanent call forward params
func (o *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams) SetNumber(number string) {
	o.Number = number
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIRestServiceUpdatePermanentCallForwardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Forward != nil {
		if err := r.SetBodyParam(o.Forward); err != nil {
			return err
		}
	}

	// path param number
	if err := r.SetPathParam("number", o.Number); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
