// Code generated by go-swagger; DO NOT EDIT.

package permanent_call_forwards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIWebServiceAddPermanentCallForwardReader is a Reader for the ThinkteluControlAPIWebServiceAddPermanentCallForward structure.
type ThinkteluControlAPIWebServiceAddPermanentCallForwardReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIWebServiceAddPermanentCallForwardReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIWebServiceAddPermanentCallForwardOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIWebServiceAddPermanentCallForwardDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIWebServiceAddPermanentCallForwardOK creates a ThinktelUControlAPIWebServiceAddPermanentCallForwardOK with default headers values
func NewThinktelUControlAPIWebServiceAddPermanentCallForwardOK() *ThinktelUControlAPIWebServiceAddPermanentCallForwardOK {
	return &ThinktelUControlAPIWebServiceAddPermanentCallForwardOK{}
}

/*
ThinktelUControlAPIWebServiceAddPermanentCallForwardOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIWebServiceAddPermanentCallForwardOK struct {
	Payload *models.ThinkteluControlAPIDataContractsNumberResponse
}

// IsSuccess returns true when this thinktel u control Api web service add permanent call forward o k response has a 2xx status code
func (o *ThinktelUControlAPIWebServiceAddPermanentCallForwardOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api web service add permanent call forward o k response has a 3xx status code
func (o *ThinktelUControlAPIWebServiceAddPermanentCallForwardOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api web service add permanent call forward o k response has a 4xx status code
func (o *ThinktelUControlAPIWebServiceAddPermanentCallForwardOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api web service add permanent call forward o k response has a 5xx status code
func (o *ThinktelUControlAPIWebServiceAddPermanentCallForwardOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api web service add permanent call forward o k response a status code equal to that given
func (o *ThinktelUControlAPIWebServiceAddPermanentCallForwardOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api web service add permanent call forward o k response
func (o *ThinktelUControlAPIWebServiceAddPermanentCallForwardOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIWebServiceAddPermanentCallForwardOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /PermanentCallForwards][%d] thinktelUControlApiWebServiceAddPermanentCallForwardOK %s", 200, payload)
}

func (o *ThinktelUControlAPIWebServiceAddPermanentCallForwardOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /PermanentCallForwards][%d] thinktelUControlApiWebServiceAddPermanentCallForwardOK %s", 200, payload)
}

func (o *ThinktelUControlAPIWebServiceAddPermanentCallForwardOK) GetPayload() *models.ThinkteluControlAPIDataContractsNumberResponse {
	return o.Payload
}

func (o *ThinktelUControlAPIWebServiceAddPermanentCallForwardOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsNumberResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIWebServiceAddPermanentCallForwardDefault creates a ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault with default headers values
func NewThinkteluControlAPIWebServiceAddPermanentCallForwardDefault(code int) *ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault {
	return &ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api web service add permanent call forward default response has a 2xx status code
func (o *ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api web service add permanent call forward default response has a 3xx status code
func (o *ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api web service add permanent call forward default response has a 4xx status code
func (o *ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api web service add permanent call forward default response has a 5xx status code
func (o *ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api web service add permanent call forward default response a status code equal to that given
func (o *ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api web service add permanent call forward default response
func (o *ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /PermanentCallForwards][%d] Thinktel.uControl.Api.WebService.AddPermanentCallForward default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /PermanentCallForwards][%d] Thinktel.uControl.Api.WebService.AddPermanentCallForward default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIWebServiceAddPermanentCallForwardDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
