// Code generated by go-swagger; DO NOT EDIT.

package sip_trunks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIRestServiceCancelSIPTrunkLineReader is a Reader for the ThinkteluControlAPIRestServiceCancelSIPTrunkLine structure.
type ThinkteluControlAPIRestServiceCancelSIPTrunkLineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIRestServiceCancelSIPTrunkLineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIRestServiceCancelSIPTrunkLineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIRestServiceCancelSIPTrunkLineOK creates a ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK with default headers values
func NewThinktelUControlAPIRestServiceCancelSIPTrunkLineOK() *ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK {
	return &ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK{}
}

/*
ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK struct {
	Payload *models.ThinkteluControlAPIDataContractsNumberResponse
}

// IsSuccess returns true when this thinktel u control Api rest service cancel Sip trunk line o k response has a 2xx status code
func (o *ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api rest service cancel Sip trunk line o k response has a 3xx status code
func (o *ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api rest service cancel Sip trunk line o k response has a 4xx status code
func (o *ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api rest service cancel Sip trunk line o k response has a 5xx status code
func (o *ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api rest service cancel Sip trunk line o k response a status code equal to that given
func (o *ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api rest service cancel Sip trunk line o k response
func (o *ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /SipTrunks/{number}/Lines/{SipBindingID}][%d] thinktelUControlApiRestServiceCancelSipTrunkLineOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /SipTrunks/{number}/Lines/{SipBindingID}][%d] thinktelUControlApiRestServiceCancelSipTrunkLineOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK) GetPayload() *models.ThinkteluControlAPIDataContractsNumberResponse {
	return o.Payload
}

func (o *ThinktelUControlAPIRestServiceCancelSIPTrunkLineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsNumberResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault creates a ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault with default headers values
func NewThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault(code int) *ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault {
	return &ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api rest service cancel Sip trunk line default response has a 2xx status code
func (o *ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api rest service cancel Sip trunk line default response has a 3xx status code
func (o *ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api rest service cancel Sip trunk line default response has a 4xx status code
func (o *ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api rest service cancel Sip trunk line default response has a 5xx status code
func (o *ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api rest service cancel Sip trunk line default response a status code equal to that given
func (o *ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api rest service cancel Sip trunk line default response
func (o *ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /SipTrunks/{number}/Lines/{SipBindingID}][%d] Thinktel.uControl.Api.RestService.CancelSipTrunkLine default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /SipTrunks/{number}/Lines/{SipBindingID}][%d] Thinktel.uControl.Api.RestService.CancelSipTrunkLine default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIRestServiceCancelSIPTrunkLineDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
