// Code generated by go-swagger; DO NOT EDIT.

package sip_trunks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesReader is a Reader for the ThinkteluControlAPIRestServiceGetSubscriberPremiumFeatures structure.
type ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK creates a ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK with default headers values
func NewThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK() *ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK {
	return &ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK{}
}

/*
ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK struct {
	Payload *models.ThinkteluControlAPIDataContractsSubscriberSIPTrunkFeatures
}

// IsSuccess returns true when this thinktel u control Api rest service get subscriber premium features o k response has a 2xx status code
func (o *ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api rest service get subscriber premium features o k response has a 3xx status code
func (o *ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api rest service get subscriber premium features o k response has a 4xx status code
func (o *ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api rest service get subscriber premium features o k response has a 5xx status code
func (o *ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api rest service get subscriber premium features o k response a status code equal to that given
func (o *ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api rest service get subscriber premium features o k response
func (o *ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{pilot}/PremiumFeatures][%d] thinktelUControlApiRestServiceGetSubscriberPremiumFeaturesOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{pilot}/PremiumFeatures][%d] thinktelUControlApiRestServiceGetSubscriberPremiumFeaturesOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK) GetPayload() *models.ThinkteluControlAPIDataContractsSubscriberSIPTrunkFeatures {
	return o.Payload
}

func (o *ThinktelUControlAPIRestServiceGetSubscriberPremiumFeaturesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsSubscriberSIPTrunkFeatures)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault creates a ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault with default headers values
func NewThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault(code int) *ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault {
	return &ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api rest service get subscriber premium features default response has a 2xx status code
func (o *ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api rest service get subscriber premium features default response has a 3xx status code
func (o *ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api rest service get subscriber premium features default response has a 4xx status code
func (o *ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api rest service get subscriber premium features default response has a 5xx status code
func (o *ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api rest service get subscriber premium features default response a status code equal to that given
func (o *ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api rest service get subscriber premium features default response
func (o *ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{pilot}/PremiumFeatures][%d] Thinktel.uControl.Api.RestService.GetSubscriberPremiumFeatures default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{pilot}/PremiumFeatures][%d] Thinktel.uControl.Api.RestService.GetSubscriberPremiumFeatures default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIRestServiceGetSubscriberPremiumFeaturesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
