// Code generated by go-swagger; DO NOT EDIT.

package sip_trunks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewThinkteluControlAPIRestServiceListSIPTrunkDidsParams creates a new ThinkteluControlAPIRestServiceListSIPTrunkDidsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIRestServiceListSIPTrunkDidsParams() *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams {
	return &ThinkteluControlAPIRestServiceListSIPTrunkDidsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIRestServiceListSIPTrunkDidsParamsWithTimeout creates a new ThinkteluControlAPIRestServiceListSIPTrunkDidsParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIRestServiceListSIPTrunkDidsParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams {
	return &ThinkteluControlAPIRestServiceListSIPTrunkDidsParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIRestServiceListSIPTrunkDidsParamsWithContext creates a new ThinkteluControlAPIRestServiceListSIPTrunkDidsParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIRestServiceListSIPTrunkDidsParamsWithContext(ctx context.Context) *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams {
	return &ThinkteluControlAPIRestServiceListSIPTrunkDidsParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIRestServiceListSIPTrunkDidsParamsWithHTTPClient creates a new ThinkteluControlAPIRestServiceListSIPTrunkDidsParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIRestServiceListSIPTrunkDidsParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams {
	return &ThinkteluControlAPIRestServiceListSIPTrunkDidsParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIRestServiceListSIPTrunkDidsParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api rest service list Sip trunk dids operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIRestServiceListSIPTrunkDidsParams struct {

	/* PageFrom.

	   Last DID from previous results, or 0 if starting at beginning.
	*/
	PageFrom string

	/* PageSize.

	   Maximum number of DIDs provided in results.
	*/
	PageSize string

	/* Number.

	   SIP trunk pilot directory number.
	*/
	Number string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api rest service list Sip trunk dids params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) WithDefaults() *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api rest service list Sip trunk dids params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api rest service list Sip trunk dids params
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api rest service list Sip trunk dids params
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api rest service list Sip trunk dids params
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) WithContext(ctx context.Context) *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api rest service list Sip trunk dids params
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api rest service list Sip trunk dids params
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api rest service list Sip trunk dids params
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPageFrom adds the pageFrom to the thinktel u control Api rest service list Sip trunk dids params
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) WithPageFrom(pageFrom string) *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams {
	o.SetPageFrom(pageFrom)
	return o
}

// SetPageFrom adds the pageFrom to the thinktel u control Api rest service list Sip trunk dids params
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) SetPageFrom(pageFrom string) {
	o.PageFrom = pageFrom
}

// WithPageSize adds the pageSize to the thinktel u control Api rest service list Sip trunk dids params
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) WithPageSize(pageSize string) *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the thinktel u control Api rest service list Sip trunk dids params
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) SetPageSize(pageSize string) {
	o.PageSize = pageSize
}

// WithNumber adds the number to the thinktel u control Api rest service list Sip trunk dids params
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) WithNumber(number string) *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the thinktel u control Api rest service list Sip trunk dids params
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) SetNumber(number string) {
	o.Number = number
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param PageFrom
	qrPageFrom := o.PageFrom
	qPageFrom := qrPageFrom
	if qPageFrom != "" {

		if err := r.SetQueryParam("PageFrom", qPageFrom); err != nil {
			return err
		}
	}

	// query param PageSize
	qrPageSize := o.PageSize
	qPageSize := qrPageSize
	if qPageSize != "" {

		if err := r.SetQueryParam("PageSize", qPageSize); err != nil {
			return err
		}
	}

	// path param number
	if err := r.SetPathParam("number", o.Number); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
