// Code generated by go-swagger; DO NOT EDIT.

package sip_trunks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIRestServiceListSIPTrunkLinesReader is a Reader for the ThinkteluControlAPIRestServiceListSIPTrunkLines structure.
type ThinkteluControlAPIRestServiceListSIPTrunkLinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIRestServiceListSIPTrunkLinesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIRestServiceListSIPTrunkLinesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIRestServiceListSIPTrunkLinesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIRestServiceListSIPTrunkLinesOK creates a ThinktelUControlAPIRestServiceListSIPTrunkLinesOK with default headers values
func NewThinktelUControlAPIRestServiceListSIPTrunkLinesOK() *ThinktelUControlAPIRestServiceListSIPTrunkLinesOK {
	return &ThinktelUControlAPIRestServiceListSIPTrunkLinesOK{}
}

/*
ThinktelUControlAPIRestServiceListSIPTrunkLinesOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIRestServiceListSIPTrunkLinesOK struct {
	Payload []*models.ThinkteluControlAPIDataContractsSIPTrunkLine
}

// IsSuccess returns true when this thinktel u control Api rest service list Sip trunk lines o k response has a 2xx status code
func (o *ThinktelUControlAPIRestServiceListSIPTrunkLinesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api rest service list Sip trunk lines o k response has a 3xx status code
func (o *ThinktelUControlAPIRestServiceListSIPTrunkLinesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api rest service list Sip trunk lines o k response has a 4xx status code
func (o *ThinktelUControlAPIRestServiceListSIPTrunkLinesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api rest service list Sip trunk lines o k response has a 5xx status code
func (o *ThinktelUControlAPIRestServiceListSIPTrunkLinesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api rest service list Sip trunk lines o k response a status code equal to that given
func (o *ThinktelUControlAPIRestServiceListSIPTrunkLinesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api rest service list Sip trunk lines o k response
func (o *ThinktelUControlAPIRestServiceListSIPTrunkLinesOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIRestServiceListSIPTrunkLinesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{number}/Lines][%d] thinktelUControlApiRestServiceListSipTrunkLinesOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceListSIPTrunkLinesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{number}/Lines][%d] thinktelUControlApiRestServiceListSipTrunkLinesOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceListSIPTrunkLinesOK) GetPayload() []*models.ThinkteluControlAPIDataContractsSIPTrunkLine {
	return o.Payload
}

func (o *ThinktelUControlAPIRestServiceListSIPTrunkLinesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIRestServiceListSIPTrunkLinesDefault creates a ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault with default headers values
func NewThinkteluControlAPIRestServiceListSIPTrunkLinesDefault(code int) *ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault {
	return &ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api rest service list Sip trunk lines default response has a 2xx status code
func (o *ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api rest service list Sip trunk lines default response has a 3xx status code
func (o *ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api rest service list Sip trunk lines default response has a 4xx status code
func (o *ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api rest service list Sip trunk lines default response has a 5xx status code
func (o *ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api rest service list Sip trunk lines default response a status code equal to that given
func (o *ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api rest service list Sip trunk lines default response
func (o *ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{number}/Lines][%d] Thinktel.uControl.Api.RestService.ListSipTrunkLines default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{number}/Lines][%d] Thinktel.uControl.Api.RestService.ListSipTrunkLines default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIRestServiceListSIPTrunkLinesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
