// Code generated by go-swagger; DO NOT EDIT.

package sip_trunks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIRestServiceListSIPTrunkRateCentersReader is a Reader for the ThinkteluControlAPIRestServiceListSIPTrunkRateCenters structure.
type ThinkteluControlAPIRestServiceListSIPTrunkRateCentersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIRestServiceListSIPTrunkRateCentersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK creates a ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK with default headers values
func NewThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK() *ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK {
	return &ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK{}
}

/*
ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK struct {
	Payload []*models.ThinkteluControlAPIDataContractsTerseRateCenter
}

// IsSuccess returns true when this thinktel u control Api rest service list Sip trunk rate centers o k response has a 2xx status code
func (o *ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api rest service list Sip trunk rate centers o k response has a 3xx status code
func (o *ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api rest service list Sip trunk rate centers o k response has a 4xx status code
func (o *ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api rest service list Sip trunk rate centers o k response has a 5xx status code
func (o *ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api rest service list Sip trunk rate centers o k response a status code equal to that given
func (o *ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api rest service list Sip trunk rate centers o k response
func (o *ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{number}/RateCenters][%d] thinktelUControlApiRestServiceListSipTrunkRateCentersOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{number}/RateCenters][%d] thinktelUControlApiRestServiceListSipTrunkRateCentersOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK) GetPayload() []*models.ThinkteluControlAPIDataContractsTerseRateCenter {
	return o.Payload
}

func (o *ThinktelUControlAPIRestServiceListSIPTrunkRateCentersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault creates a ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault with default headers values
func NewThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault(code int) *ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault {
	return &ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api rest service list Sip trunk rate centers default response has a 2xx status code
func (o *ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api rest service list Sip trunk rate centers default response has a 3xx status code
func (o *ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api rest service list Sip trunk rate centers default response has a 4xx status code
func (o *ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api rest service list Sip trunk rate centers default response has a 5xx status code
func (o *ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api rest service list Sip trunk rate centers default response a status code equal to that given
func (o *ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api rest service list Sip trunk rate centers default response
func (o *ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{number}/RateCenters][%d] Thinktel.uControl.Api.RestService.ListSipTrunkRateCenters default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{number}/RateCenters][%d] Thinktel.uControl.Api.RestService.ListSipTrunkRateCenters default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIRestServiceListSIPTrunkRateCentersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
