// Code generated by go-swagger; DO NOT EDIT.

package sip_trunks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIRestServiceListSIPTrunkDidsReader is a Reader for the ThinkteluControlAPIRestServiceListSIPTrunkDids structure.
type ThinkteluControlAPIRestServiceListSIPTrunkDidsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIRestServiceListSIPTrunkDidsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIRestServiceListSIPTrunkDidsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIRestServiceListSIPTrunkDidsOK creates a ThinktelUControlAPIRestServiceListSIPTrunkDidsOK with default headers values
func NewThinktelUControlAPIRestServiceListSIPTrunkDidsOK() *ThinktelUControlAPIRestServiceListSIPTrunkDidsOK {
	return &ThinktelUControlAPIRestServiceListSIPTrunkDidsOK{}
}

/*
ThinktelUControlAPIRestServiceListSIPTrunkDidsOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIRestServiceListSIPTrunkDidsOK struct {
	Payload []*models.ThinkteluControlAPIDataContractsTerseNumber
}

// IsSuccess returns true when this thinktel u control Api rest service list Sip trunk dids o k response has a 2xx status code
func (o *ThinktelUControlAPIRestServiceListSIPTrunkDidsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api rest service list Sip trunk dids o k response has a 3xx status code
func (o *ThinktelUControlAPIRestServiceListSIPTrunkDidsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api rest service list Sip trunk dids o k response has a 4xx status code
func (o *ThinktelUControlAPIRestServiceListSIPTrunkDidsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api rest service list Sip trunk dids o k response has a 5xx status code
func (o *ThinktelUControlAPIRestServiceListSIPTrunkDidsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api rest service list Sip trunk dids o k response a status code equal to that given
func (o *ThinktelUControlAPIRestServiceListSIPTrunkDidsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api rest service list Sip trunk dids o k response
func (o *ThinktelUControlAPIRestServiceListSIPTrunkDidsOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIRestServiceListSIPTrunkDidsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{number}/Dids][%d] thinktelUControlApiRestServiceListSipTrunkDidsOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceListSIPTrunkDidsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{number}/Dids][%d] thinktelUControlApiRestServiceListSipTrunkDidsOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceListSIPTrunkDidsOK) GetPayload() []*models.ThinkteluControlAPIDataContractsTerseNumber {
	return o.Payload
}

func (o *ThinktelUControlAPIRestServiceListSIPTrunkDidsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIRestServiceListSIPTrunkDidsDefault creates a ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault with default headers values
func NewThinkteluControlAPIRestServiceListSIPTrunkDidsDefault(code int) *ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault {
	return &ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api rest service list Sip trunk dids default response has a 2xx status code
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api rest service list Sip trunk dids default response has a 3xx status code
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api rest service list Sip trunk dids default response has a 4xx status code
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api rest service list Sip trunk dids default response has a 5xx status code
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api rest service list Sip trunk dids default response a status code equal to that given
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api rest service list Sip trunk dids default response
func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{number}/Dids][%d] Thinktel.uControl.Api.RestService.ListSipTrunkDids default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipTrunks/{number}/Dids][%d] Thinktel.uControl.Api.RestService.ListSipTrunkDids default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIRestServiceListSIPTrunkDidsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
