// Code generated by go-swagger; DO NOT EDIT.

package sip_trunks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams creates a new ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams() *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams {
	return &ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParamsWithTimeout creates a new ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams {
	return &ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParamsWithContext creates a new ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParamsWithContext(ctx context.Context) *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams {
	return &ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParamsWithHTTPClient creates a new ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams {
	return &ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api rest service get DID premium features operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams struct {

	/* Number.

	   DID number.
	*/
	Number string

	/* Pilot.

	   SIP trunk directory number.
	*/
	Pilot string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api rest service get DID premium features params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams) WithDefaults() *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api rest service get DID premium features params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api rest service get DID premium features params
func (o *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api rest service get DID premium features params
func (o *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api rest service get DID premium features params
func (o *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams) WithContext(ctx context.Context) *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api rest service get DID premium features params
func (o *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api rest service get DID premium features params
func (o *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api rest service get DID premium features params
func (o *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNumber adds the number to the thinktel u control Api rest service get DID premium features params
func (o *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams) WithNumber(number string) *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the thinktel u control Api rest service get DID premium features params
func (o *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams) SetNumber(number string) {
	o.Number = number
}

// WithPilot adds the pilot to the thinktel u control Api rest service get DID premium features params
func (o *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams) WithPilot(pilot string) *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams {
	o.SetPilot(pilot)
	return o
}

// SetPilot adds the pilot to the thinktel u control Api rest service get DID premium features params
func (o *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams) SetPilot(pilot string) {
	o.Pilot = pilot
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIRestServiceGetDIDPremiumFeaturesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param number
	if err := r.SetPathParam("number", o.Number); err != nil {
		return err
	}

	// path param pilot
	if err := r.SetPathParam("pilot", o.Pilot); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
