// Code generated by go-swagger; DO NOT EDIT.

package version911

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIRestServiceGetV911v2Reader is a Reader for the ThinkteluControlAPIRestServiceGetV911v2 structure.
type ThinkteluControlAPIRestServiceGetV911v2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIRestServiceGetV911v2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIRestServiceGetV911v2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIRestServiceGetV911v2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIRestServiceGetV911v2OK creates a ThinktelUControlAPIRestServiceGetV911v2OK with default headers values
func NewThinktelUControlAPIRestServiceGetV911v2OK() *ThinktelUControlAPIRestServiceGetV911v2OK {
	return &ThinktelUControlAPIRestServiceGetV911v2OK{}
}

/*
ThinktelUControlAPIRestServiceGetV911v2OK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIRestServiceGetV911v2OK struct {
	Payload *models.ThinkteluControlAPIDataContractsV911v2
}

// IsSuccess returns true when this thinktel u control Api rest service get v911v2 o k response has a 2xx status code
func (o *ThinktelUControlAPIRestServiceGetV911v2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api rest service get v911v2 o k response has a 3xx status code
func (o *ThinktelUControlAPIRestServiceGetV911v2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api rest service get v911v2 o k response has a 4xx status code
func (o *ThinktelUControlAPIRestServiceGetV911v2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api rest service get v911v2 o k response has a 5xx status code
func (o *ThinktelUControlAPIRestServiceGetV911v2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api rest service get v911v2 o k response a status code equal to that given
func (o *ThinktelUControlAPIRestServiceGetV911v2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api rest service get v911v2 o k response
func (o *ThinktelUControlAPIRestServiceGetV911v2OK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIRestServiceGetV911v2OK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v2/V911s/{number}][%d] thinktelUControlApiRestServiceGetV911v2OK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceGetV911v2OK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v2/V911s/{number}][%d] thinktelUControlApiRestServiceGetV911v2OK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceGetV911v2OK) GetPayload() *models.ThinkteluControlAPIDataContractsV911v2 {
	return o.Payload
}

func (o *ThinktelUControlAPIRestServiceGetV911v2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsV911v2)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIRestServiceGetV911v2Default creates a ThinkteluControlAPIRestServiceGetV911v2Default with default headers values
func NewThinkteluControlAPIRestServiceGetV911v2Default(code int) *ThinkteluControlAPIRestServiceGetV911v2Default {
	return &ThinkteluControlAPIRestServiceGetV911v2Default{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIRestServiceGetV911v2Default describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIRestServiceGetV911v2Default struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api rest service get v911v2 default response has a 2xx status code
func (o *ThinkteluControlAPIRestServiceGetV911v2Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api rest service get v911v2 default response has a 3xx status code
func (o *ThinkteluControlAPIRestServiceGetV911v2Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api rest service get v911v2 default response has a 4xx status code
func (o *ThinkteluControlAPIRestServiceGetV911v2Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api rest service get v911v2 default response has a 5xx status code
func (o *ThinkteluControlAPIRestServiceGetV911v2Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api rest service get v911v2 default response a status code equal to that given
func (o *ThinkteluControlAPIRestServiceGetV911v2Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api rest service get v911v2 default response
func (o *ThinkteluControlAPIRestServiceGetV911v2Default) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIRestServiceGetV911v2Default) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v2/V911s/{number}][%d] Thinktel.uControl.Api.RestService.GetV911v2 default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceGetV911v2Default) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v2/V911s/{number}][%d] Thinktel.uControl.Api.RestService.GetV911v2 default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceGetV911v2Default) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIRestServiceGetV911v2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
