// Code generated by go-swagger; DO NOT EDIT.

package surecall_sip_trunks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewThinkteluControlAPIWebServiceGetSurecallParams creates a new ThinkteluControlAPIWebServiceGetSurecallParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIWebServiceGetSurecallParams() *ThinkteluControlAPIWebServiceGetSurecallParams {
	return &ThinkteluControlAPIWebServiceGetSurecallParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIWebServiceGetSurecallParamsWithTimeout creates a new ThinkteluControlAPIWebServiceGetSurecallParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIWebServiceGetSurecallParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceGetSurecallParams {
	return &ThinkteluControlAPIWebServiceGetSurecallParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIWebServiceGetSurecallParamsWithContext creates a new ThinkteluControlAPIWebServiceGetSurecallParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIWebServiceGetSurecallParamsWithContext(ctx context.Context) *ThinkteluControlAPIWebServiceGetSurecallParams {
	return &ThinkteluControlAPIWebServiceGetSurecallParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIWebServiceGetSurecallParamsWithHTTPClient creates a new ThinkteluControlAPIWebServiceGetSurecallParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIWebServiceGetSurecallParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceGetSurecallParams {
	return &ThinkteluControlAPIWebServiceGetSurecallParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIWebServiceGetSurecallParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api web service get surecall operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIWebServiceGetSurecallParams struct {

	/* Pilot.

	   SIP trunk pilot directory number.
	*/
	Pilot string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api web service get surecall params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceGetSurecallParams) WithDefaults() *ThinkteluControlAPIWebServiceGetSurecallParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api web service get surecall params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceGetSurecallParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api web service get surecall params
func (o *ThinkteluControlAPIWebServiceGetSurecallParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceGetSurecallParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api web service get surecall params
func (o *ThinkteluControlAPIWebServiceGetSurecallParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api web service get surecall params
func (o *ThinkteluControlAPIWebServiceGetSurecallParams) WithContext(ctx context.Context) *ThinkteluControlAPIWebServiceGetSurecallParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api web service get surecall params
func (o *ThinkteluControlAPIWebServiceGetSurecallParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api web service get surecall params
func (o *ThinkteluControlAPIWebServiceGetSurecallParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceGetSurecallParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api web service get surecall params
func (o *ThinkteluControlAPIWebServiceGetSurecallParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPilot adds the pilot to the thinktel u control Api web service get surecall params
func (o *ThinkteluControlAPIWebServiceGetSurecallParams) WithPilot(pilot string) *ThinkteluControlAPIWebServiceGetSurecallParams {
	o.SetPilot(pilot)
	return o
}

// SetPilot adds the pilot to the thinktel u control Api web service get surecall params
func (o *ThinkteluControlAPIWebServiceGetSurecallParams) SetPilot(pilot string) {
	o.Pilot = pilot
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIWebServiceGetSurecallParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param pilot
	if err := r.SetPathParam("pilot", o.Pilot); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
