// Code generated by go-swagger; DO NOT EDIT.

package porting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params creates a new ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params() *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params {
	return &ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2ParamsWithTimeout creates a new ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2ParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params {
	return &ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2ParamsWithContext creates a new ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params object
// with the ability to set a context for a request.
func NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2ParamsWithContext(ctx context.Context) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params {
	return &ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params{
		Context: ctx,
	}
}

// NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2ParamsWithHTTPClient creates a new ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2ParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params {
	return &ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params contains all the parameters to send to the API endpoint

	for the thinktel u control Api web service add number port business line v2 operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params struct {

	/* OrderForm.

	   Business line port-in order.
	*/
	OrderForm *models.ThinkteluControlAPIDataContractsNumberPortOrderBusinessLineV2

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api web service add number port business line v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params) WithDefaults() *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api web service add number port business line v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api web service add number port business line v2 params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params) WithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api web service add number port business line v2 params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api web service add number port business line v2 params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params) WithContext(ctx context.Context) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api web service add number port business line v2 params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api web service add number port business line v2 params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params) WithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api web service add number port business line v2 params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderForm adds the orderForm to the thinktel u control Api web service add number port business line v2 params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params) WithOrderForm(orderForm *models.ThinkteluControlAPIDataContractsNumberPortOrderBusinessLineV2) *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params {
	o.SetOrderForm(orderForm)
	return o
}

// SetOrderForm adds the orderForm to the thinktel u control Api web service add number port business line v2 params
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params) SetOrderForm(orderForm *models.ThinkteluControlAPIDataContractsNumberPortOrderBusinessLineV2) {
	o.OrderForm = orderForm
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIWebServiceAddNumberPortBusinessLineV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.OrderForm != nil {
		if err := r.SetBodyParam(o.OrderForm); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
