// Code generated by go-swagger; DO NOT EDIT.

package porting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// NewThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams creates a new ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams() *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams {
	return &ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParamsWithTimeout creates a new ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams {
	return &ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParamsWithContext creates a new ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParamsWithContext(ctx context.Context) *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams {
	return &ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParamsWithHTTPClient creates a new ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams {
	return &ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api web service add number port virtual fax operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams struct {

	/* OrderForm.

	   Virtual fax port-in order.
	*/
	OrderForm *models.ThinkteluControlAPIDataContractsNumberPortOrderVirtualFax

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api web service add number port virtual fax params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams) WithDefaults() *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api web service add number port virtual fax params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api web service add number port virtual fax params
func (o *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api web service add number port virtual fax params
func (o *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api web service add number port virtual fax params
func (o *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams) WithContext(ctx context.Context) *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api web service add number port virtual fax params
func (o *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api web service add number port virtual fax params
func (o *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api web service add number port virtual fax params
func (o *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderForm adds the orderForm to the thinktel u control Api web service add number port virtual fax params
func (o *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams) WithOrderForm(orderForm *models.ThinkteluControlAPIDataContractsNumberPortOrderVirtualFax) *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams {
	o.SetOrderForm(orderForm)
	return o
}

// SetOrderForm adds the orderForm to the thinktel u control Api web service add number port virtual fax params
func (o *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams) SetOrderForm(orderForm *models.ThinkteluControlAPIDataContractsNumberPortOrderVirtualFax) {
	o.OrderForm = orderForm
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIWebServiceAddNumberPortVirtualFaxParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.OrderForm != nil {
		if err := r.SetBodyParam(o.OrderForm); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
