// Code generated by go-swagger; DO NOT EDIT.

package porting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductReader is a Reader for the ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProduct structure.
type ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK creates a ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK with default headers values
func NewThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK() *ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK {
	return &ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK{}
}

/*
ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK struct {
	Payload *models.ThinkteluControlAPIDataContractsTicketResponse
}

// IsSuccess returns true when this thinktel u control Api web service add number port general child product o k response has a 2xx status code
func (o *ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api web service add number port general child product o k response has a 3xx status code
func (o *ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api web service add number port general child product o k response has a 4xx status code
func (o *ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api web service add number port general child product o k response has a 5xx status code
func (o *ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api web service add number port general child product o k response a status code equal to that given
func (o *ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api web service add number port general child product o k response
func (o *ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /NumberPorts/Inbound/GeneralChildProducts][%d] thinktelUControlApiWebServiceAddNumberPortGeneralChildProductOK %s", 200, payload)
}

func (o *ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /NumberPorts/Inbound/GeneralChildProducts][%d] thinktelUControlApiWebServiceAddNumberPortGeneralChildProductOK %s", 200, payload)
}

func (o *ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK) GetPayload() *models.ThinkteluControlAPIDataContractsTicketResponse {
	return o.Payload
}

func (o *ThinktelUControlAPIWebServiceAddNumberPortGeneralChildProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsTicketResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault creates a ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault with default headers values
func NewThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault(code int) *ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault {
	return &ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api web service add number port general child product default response has a 2xx status code
func (o *ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api web service add number port general child product default response has a 3xx status code
func (o *ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api web service add number port general child product default response has a 4xx status code
func (o *ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api web service add number port general child product default response has a 5xx status code
func (o *ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api web service add number port general child product default response a status code equal to that given
func (o *ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api web service add number port general child product default response
func (o *ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /NumberPorts/Inbound/GeneralChildProducts][%d] Thinktel.uControl.Api.WebService.AddNumberPortGeneralChildProduct default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /NumberPorts/Inbound/GeneralChildProducts][%d] Thinktel.uControl.Api.WebService.AddNumberPortGeneralChildProduct default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIWebServiceAddNumberPortGeneralChildProductDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
