// Code generated by go-swagger; DO NOT EDIT.

package porting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams creates a new ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams() *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams {
	return &ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParamsWithTimeout creates a new ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams {
	return &ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParamsWithContext creates a new ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParamsWithContext(ctx context.Context) *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams {
	return &ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParamsWithHTTPClient creates a new ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams {
	return &ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api web service get port sys customer info by request Id operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams struct {

	/* OrderID.

	   Order Id.
	*/
	OrderID string

	/* RequestID.

	   Request Id.
	*/
	RequestID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api web service get port sys customer info by request Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams) WithDefaults() *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api web service get port sys customer info by request Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api web service get port sys customer info by request Id params
func (o *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api web service get port sys customer info by request Id params
func (o *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api web service get port sys customer info by request Id params
func (o *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams) WithContext(ctx context.Context) *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api web service get port sys customer info by request Id params
func (o *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api web service get port sys customer info by request Id params
func (o *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api web service get port sys customer info by request Id params
func (o *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderID adds the orderID to the thinktel u control Api web service get port sys customer info by request Id params
func (o *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams) WithOrderID(orderID string) *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams {
	o.SetOrderID(orderID)
	return o
}

// SetOrderID adds the orderId to the thinktel u control Api web service get port sys customer info by request Id params
func (o *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams) SetOrderID(orderID string) {
	o.OrderID = orderID
}

// WithRequestID adds the requestID to the thinktel u control Api web service get port sys customer info by request Id params
func (o *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams) WithRequestID(requestID string) *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams {
	o.SetRequestID(requestID)
	return o
}

// SetRequestID adds the requestId to the thinktel u control Api web service get port sys customer info by request Id params
func (o *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams) SetRequestID(requestID string) {
	o.RequestID = requestID
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIWebServiceGetPortSysCustomerInfoByRequestIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param OrderId
	if err := r.SetPathParam("OrderId", o.OrderID); err != nil {
		return err
	}

	// path param RequestId
	if err := r.SetPathParam("RequestId", o.RequestID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
