// Code generated by go-swagger; DO NOT EDIT.

package sip_bindings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIRestServiceUpdateSIPBindingReader is a Reader for the ThinkteluControlAPIRestServiceUpdateSIPBinding structure.
type ThinkteluControlAPIRestServiceUpdateSIPBindingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIRestServiceUpdateSIPBindingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIRestServiceUpdateSIPBindingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIRestServiceUpdateSIPBindingDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIRestServiceUpdateSIPBindingOK creates a ThinktelUControlAPIRestServiceUpdateSIPBindingOK with default headers values
func NewThinktelUControlAPIRestServiceUpdateSIPBindingOK() *ThinktelUControlAPIRestServiceUpdateSIPBindingOK {
	return &ThinktelUControlAPIRestServiceUpdateSIPBindingOK{}
}

/*
ThinktelUControlAPIRestServiceUpdateSIPBindingOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIRestServiceUpdateSIPBindingOK struct {
	Payload *models.ThinkteluControlAPIDataContractsItemResponse
}

// IsSuccess returns true when this thinktel u control Api rest service update Sip binding o k response has a 2xx status code
func (o *ThinktelUControlAPIRestServiceUpdateSIPBindingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api rest service update Sip binding o k response has a 3xx status code
func (o *ThinktelUControlAPIRestServiceUpdateSIPBindingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api rest service update Sip binding o k response has a 4xx status code
func (o *ThinktelUControlAPIRestServiceUpdateSIPBindingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api rest service update Sip binding o k response has a 5xx status code
func (o *ThinktelUControlAPIRestServiceUpdateSIPBindingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api rest service update Sip binding o k response a status code equal to that given
func (o *ThinktelUControlAPIRestServiceUpdateSIPBindingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api rest service update Sip binding o k response
func (o *ThinktelUControlAPIRestServiceUpdateSIPBindingOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIRestServiceUpdateSIPBindingOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /SipBindings/{ID}][%d] thinktelUControlApiRestServiceUpdateSipBindingOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceUpdateSIPBindingOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /SipBindings/{ID}][%d] thinktelUControlApiRestServiceUpdateSipBindingOK %s", 200, payload)
}

func (o *ThinktelUControlAPIRestServiceUpdateSIPBindingOK) GetPayload() *models.ThinkteluControlAPIDataContractsItemResponse {
	return o.Payload
}

func (o *ThinktelUControlAPIRestServiceUpdateSIPBindingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsItemResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIRestServiceUpdateSIPBindingDefault creates a ThinkteluControlAPIRestServiceUpdateSIPBindingDefault with default headers values
func NewThinkteluControlAPIRestServiceUpdateSIPBindingDefault(code int) *ThinkteluControlAPIRestServiceUpdateSIPBindingDefault {
	return &ThinkteluControlAPIRestServiceUpdateSIPBindingDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIRestServiceUpdateSIPBindingDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIRestServiceUpdateSIPBindingDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api rest service update Sip binding default response has a 2xx status code
func (o *ThinkteluControlAPIRestServiceUpdateSIPBindingDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api rest service update Sip binding default response has a 3xx status code
func (o *ThinkteluControlAPIRestServiceUpdateSIPBindingDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api rest service update Sip binding default response has a 4xx status code
func (o *ThinkteluControlAPIRestServiceUpdateSIPBindingDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api rest service update Sip binding default response has a 5xx status code
func (o *ThinkteluControlAPIRestServiceUpdateSIPBindingDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api rest service update Sip binding default response a status code equal to that given
func (o *ThinkteluControlAPIRestServiceUpdateSIPBindingDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api rest service update Sip binding default response
func (o *ThinkteluControlAPIRestServiceUpdateSIPBindingDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIRestServiceUpdateSIPBindingDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /SipBindings/{ID}][%d] Thinktel.uControl.Api.RestService.UpdateSipBinding default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceUpdateSIPBindingDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /SipBindings/{ID}][%d] Thinktel.uControl.Api.RestService.UpdateSipBinding default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIRestServiceUpdateSIPBindingDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIRestServiceUpdateSIPBindingDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
