// Code generated by go-swagger; DO NOT EDIT.

package business_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// NewThinkteluControlAPIWebServiceAddBusinessGroupParams creates a new ThinkteluControlAPIWebServiceAddBusinessGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThinkteluControlAPIWebServiceAddBusinessGroupParams() *ThinkteluControlAPIWebServiceAddBusinessGroupParams {
	return &ThinkteluControlAPIWebServiceAddBusinessGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThinkteluControlAPIWebServiceAddBusinessGroupParamsWithTimeout creates a new ThinkteluControlAPIWebServiceAddBusinessGroupParams object
// with the ability to set a timeout on a request.
func NewThinkteluControlAPIWebServiceAddBusinessGroupParamsWithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceAddBusinessGroupParams {
	return &ThinkteluControlAPIWebServiceAddBusinessGroupParams{
		timeout: timeout,
	}
}

// NewThinkteluControlAPIWebServiceAddBusinessGroupParamsWithContext creates a new ThinkteluControlAPIWebServiceAddBusinessGroupParams object
// with the ability to set a context for a request.
func NewThinkteluControlAPIWebServiceAddBusinessGroupParamsWithContext(ctx context.Context) *ThinkteluControlAPIWebServiceAddBusinessGroupParams {
	return &ThinkteluControlAPIWebServiceAddBusinessGroupParams{
		Context: ctx,
	}
}

// NewThinkteluControlAPIWebServiceAddBusinessGroupParamsWithHTTPClient creates a new ThinkteluControlAPIWebServiceAddBusinessGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewThinkteluControlAPIWebServiceAddBusinessGroupParamsWithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceAddBusinessGroupParams {
	return &ThinkteluControlAPIWebServiceAddBusinessGroupParams{
		HTTPClient: client,
	}
}

/*
ThinkteluControlAPIWebServiceAddBusinessGroupParams contains all the parameters to send to the API endpoint

	for the thinktel u control Api web service add business group operation.

	Typically these are written to a http.Request.
*/
type ThinkteluControlAPIWebServiceAddBusinessGroupParams struct {

	/* Order.

	   Business group order.
	*/
	Order *models.ThinkteluControlAPIDataContractsBusinessGroupOrder

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thinktel u control Api web service add business group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceAddBusinessGroupParams) WithDefaults() *ThinkteluControlAPIWebServiceAddBusinessGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thinktel u control Api web service add business group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThinkteluControlAPIWebServiceAddBusinessGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thinktel u control Api web service add business group params
func (o *ThinkteluControlAPIWebServiceAddBusinessGroupParams) WithTimeout(timeout time.Duration) *ThinkteluControlAPIWebServiceAddBusinessGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thinktel u control Api web service add business group params
func (o *ThinkteluControlAPIWebServiceAddBusinessGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thinktel u control Api web service add business group params
func (o *ThinkteluControlAPIWebServiceAddBusinessGroupParams) WithContext(ctx context.Context) *ThinkteluControlAPIWebServiceAddBusinessGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thinktel u control Api web service add business group params
func (o *ThinkteluControlAPIWebServiceAddBusinessGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thinktel u control Api web service add business group params
func (o *ThinkteluControlAPIWebServiceAddBusinessGroupParams) WithHTTPClient(client *http.Client) *ThinkteluControlAPIWebServiceAddBusinessGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thinktel u control Api web service add business group params
func (o *ThinkteluControlAPIWebServiceAddBusinessGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrder adds the order to the thinktel u control Api web service add business group params
func (o *ThinkteluControlAPIWebServiceAddBusinessGroupParams) WithOrder(order *models.ThinkteluControlAPIDataContractsBusinessGroupOrder) *ThinkteluControlAPIWebServiceAddBusinessGroupParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the thinktel u control Api web service add business group params
func (o *ThinkteluControlAPIWebServiceAddBusinessGroupParams) SetOrder(order *models.ThinkteluControlAPIDataContractsBusinessGroupOrder) {
	o.Order = order
}

// WriteToRequest writes these params to a swagger request
func (o *ThinkteluControlAPIWebServiceAddBusinessGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Order != nil {
		if err := r.SetBodyParam(o.Order); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
