// Code generated by go-swagger; DO NOT EDIT.

package sip_proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wr8fdy/thinktel-go-api/models"
)

// ThinkteluControlAPIWebServiceListSIPProxiesReader is a Reader for the ThinkteluControlAPIWebServiceListSIPProxies structure.
type ThinkteluControlAPIWebServiceListSIPProxiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ThinkteluControlAPIWebServiceListSIPProxiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewThinktelUControlAPIWebServiceListSIPProxiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewThinkteluControlAPIWebServiceListSIPProxiesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewThinktelUControlAPIWebServiceListSIPProxiesOK creates a ThinktelUControlAPIWebServiceListSIPProxiesOK with default headers values
func NewThinktelUControlAPIWebServiceListSIPProxiesOK() *ThinktelUControlAPIWebServiceListSIPProxiesOK {
	return &ThinktelUControlAPIWebServiceListSIPProxiesOK{}
}

/*
ThinktelUControlAPIWebServiceListSIPProxiesOK describes a response with status code 200, with default header values.

Success
*/
type ThinktelUControlAPIWebServiceListSIPProxiesOK struct {
	Payload []*models.ThinkteluControlAPIDataContractsSIPProxy
}

// IsSuccess returns true when this thinktel u control Api web service list Sip proxies o k response has a 2xx status code
func (o *ThinktelUControlAPIWebServiceListSIPProxiesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this thinktel u control Api web service list Sip proxies o k response has a 3xx status code
func (o *ThinktelUControlAPIWebServiceListSIPProxiesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this thinktel u control Api web service list Sip proxies o k response has a 4xx status code
func (o *ThinktelUControlAPIWebServiceListSIPProxiesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this thinktel u control Api web service list Sip proxies o k response has a 5xx status code
func (o *ThinktelUControlAPIWebServiceListSIPProxiesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this thinktel u control Api web service list Sip proxies o k response a status code equal to that given
func (o *ThinktelUControlAPIWebServiceListSIPProxiesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the thinktel u control Api web service list Sip proxies o k response
func (o *ThinktelUControlAPIWebServiceListSIPProxiesOK) Code() int {
	return 200
}

func (o *ThinktelUControlAPIWebServiceListSIPProxiesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipProxies][%d] thinktelUControlApiWebServiceListSipProxiesOK %s", 200, payload)
}

func (o *ThinktelUControlAPIWebServiceListSIPProxiesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipProxies][%d] thinktelUControlApiWebServiceListSipProxiesOK %s", 200, payload)
}

func (o *ThinktelUControlAPIWebServiceListSIPProxiesOK) GetPayload() []*models.ThinkteluControlAPIDataContractsSIPProxy {
	return o.Payload
}

func (o *ThinktelUControlAPIWebServiceListSIPProxiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewThinkteluControlAPIWebServiceListSIPProxiesDefault creates a ThinkteluControlAPIWebServiceListSIPProxiesDefault with default headers values
func NewThinkteluControlAPIWebServiceListSIPProxiesDefault(code int) *ThinkteluControlAPIWebServiceListSIPProxiesDefault {
	return &ThinkteluControlAPIWebServiceListSIPProxiesDefault{
		_statusCode: code,
	}
}

/*
ThinkteluControlAPIWebServiceListSIPProxiesDefault describes a response with status code -1, with default header values.

Error
*/
type ThinkteluControlAPIWebServiceListSIPProxiesDefault struct {
	_statusCode int

	Payload *models.ThinkteluControlAPIDataContractsException
}

// IsSuccess returns true when this thinktel u control Api web service list Sip proxies default response has a 2xx status code
func (o *ThinkteluControlAPIWebServiceListSIPProxiesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this thinktel u control Api web service list Sip proxies default response has a 3xx status code
func (o *ThinkteluControlAPIWebServiceListSIPProxiesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this thinktel u control Api web service list Sip proxies default response has a 4xx status code
func (o *ThinkteluControlAPIWebServiceListSIPProxiesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this thinktel u control Api web service list Sip proxies default response has a 5xx status code
func (o *ThinkteluControlAPIWebServiceListSIPProxiesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this thinktel u control Api web service list Sip proxies default response a status code equal to that given
func (o *ThinkteluControlAPIWebServiceListSIPProxiesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the thinktel u control Api web service list Sip proxies default response
func (o *ThinkteluControlAPIWebServiceListSIPProxiesDefault) Code() int {
	return o._statusCode
}

func (o *ThinkteluControlAPIWebServiceListSIPProxiesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipProxies][%d] Thinktel.uControl.Api.WebService.ListSipProxies default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIWebServiceListSIPProxiesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /SipProxies][%d] Thinktel.uControl.Api.WebService.ListSipProxies default %s", o._statusCode, payload)
}

func (o *ThinkteluControlAPIWebServiceListSIPProxiesDefault) GetPayload() *models.ThinkteluControlAPIDataContractsException {
	return o.Payload
}

func (o *ThinkteluControlAPIWebServiceListSIPProxiesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ThinkteluControlAPIDataContractsException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
