// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ThinkteluControlAPIDataContractsNumberPortOrderGeneralProduct thinktel u control Api data contracts number port order general product
//
// swagger:model Thinktel.uControl.Api.DataContracts.NumberPortOrderGeneralProduct
type ThinkteluControlAPIDataContractsNumberPortOrderGeneralProduct struct {

	// Product offering being ordered.
	// Required: true
	OfferingID *string `json:"OfferingID"`

	// port form
	// Required: true
	PortForm *ThinkteluControlAPIDataContractsNumberPortOrderFormV2 `json:"PortForm"`
}

// Validate validates this thinktel u control Api data contracts number port order general product
func (m *ThinkteluControlAPIDataContractsNumberPortOrderGeneralProduct) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOfferingID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePortForm(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ThinkteluControlAPIDataContractsNumberPortOrderGeneralProduct) validateOfferingID(formats strfmt.Registry) error {

	if err := validate.Required("OfferingID", "body", m.OfferingID); err != nil {
		return err
	}

	return nil
}

func (m *ThinkteluControlAPIDataContractsNumberPortOrderGeneralProduct) validatePortForm(formats strfmt.Registry) error {

	if err := validate.Required("PortForm", "body", m.PortForm); err != nil {
		return err
	}

	if m.PortForm != nil {
		if err := m.PortForm.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("PortForm")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("PortForm")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this thinktel u control Api data contracts number port order general product based on the context it is used
func (m *ThinkteluControlAPIDataContractsNumberPortOrderGeneralProduct) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePortForm(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ThinkteluControlAPIDataContractsNumberPortOrderGeneralProduct) contextValidatePortForm(ctx context.Context, formats strfmt.Registry) error {

	if m.PortForm != nil {

		if err := m.PortForm.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("PortForm")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("PortForm")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsNumberPortOrderGeneralProduct) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsNumberPortOrderGeneralProduct) UnmarshalBinary(b []byte) error {
	var res ThinkteluControlAPIDataContractsNumberPortOrderGeneralProduct
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
