// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ThinkteluControlAPIDataContractsNumberPortOrderResidentialLine Telephone numbers port-in request form for residential (aka standalone) line service.
//
// swagger:model Thinktel.uControl.Api.DataContracts.NumberPortOrderResidentialLine
type ThinkteluControlAPIDataContractsNumberPortOrderResidentialLine struct {

	// Residential (aka standalone) line services to be created at end of port-in process.
	// Required: true
	Lines []*ThinkteluControlAPIDataContractsResidentialLineOrder `json:"Lines"`

	// port form
	// Required: true
	PortForm *ThinkteluControlAPIDataContractsNumberPortOrderForm `json:"PortForm"`
}

// Validate validates this thinktel u control Api data contracts number port order residential line
func (m *ThinkteluControlAPIDataContractsNumberPortOrderResidentialLine) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLines(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePortForm(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ThinkteluControlAPIDataContractsNumberPortOrderResidentialLine) validateLines(formats strfmt.Registry) error {

	if err := validate.Required("Lines", "body", m.Lines); err != nil {
		return err
	}

	for i := 0; i < len(m.Lines); i++ {
		if swag.IsZero(m.Lines[i]) { // not required
			continue
		}

		if m.Lines[i] != nil {
			if err := m.Lines[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Lines" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Lines" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ThinkteluControlAPIDataContractsNumberPortOrderResidentialLine) validatePortForm(formats strfmt.Registry) error {

	if err := validate.Required("PortForm", "body", m.PortForm); err != nil {
		return err
	}

	if m.PortForm != nil {
		if err := m.PortForm.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("PortForm")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("PortForm")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this thinktel u control Api data contracts number port order residential line based on the context it is used
func (m *ThinkteluControlAPIDataContractsNumberPortOrderResidentialLine) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLines(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePortForm(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ThinkteluControlAPIDataContractsNumberPortOrderResidentialLine) contextValidateLines(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Lines); i++ {

		if m.Lines[i] != nil {

			if swag.IsZero(m.Lines[i]) { // not required
				return nil
			}

			if err := m.Lines[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Lines" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Lines" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ThinkteluControlAPIDataContractsNumberPortOrderResidentialLine) contextValidatePortForm(ctx context.Context, formats strfmt.Registry) error {

	if m.PortForm != nil {

		if err := m.PortForm.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("PortForm")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("PortForm")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsNumberPortOrderResidentialLine) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsNumberPortOrderResidentialLine) UnmarshalBinary(b []byte) error {
	var res ThinkteluControlAPIDataContractsNumberPortOrderResidentialLine
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
