// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ThinkteluControlAPIDataContractsNameResponse thinktel u control Api data contracts name response
//
// swagger:model Thinktel.uControl.Api.DataContracts.NameResponse
type ThinkteluControlAPIDataContractsNameResponse struct {

	// message
	Message string `json:"Message,omitempty"`

	// name
	// Required: true
	Name *string `json:"Name"`

	//
	//
	//     Rejected = 0
	//     Accepted = 1
	//     Deferred = 2
	//     Conditional = 3
	//     Error = 4
	//
	// Required: true
	Reply *int64 `json:"Reply"`
}

// Validate validates this thinktel u control Api data contracts name response
func (m *ThinkteluControlAPIDataContractsNameResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReply(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ThinkteluControlAPIDataContractsNameResponse) validateName(formats strfmt.Registry) error {

	if err := validate.Required("Name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *ThinkteluControlAPIDataContractsNameResponse) validateReply(formats strfmt.Registry) error {

	if err := validate.Required("Reply", "body", m.Reply); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this thinktel u control Api data contracts name response based on context it is used
func (m *ThinkteluControlAPIDataContractsNameResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsNameResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsNameResponse) UnmarshalBinary(b []byte) error {
	var res ThinkteluControlAPIDataContractsNameResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
