// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ThinkteluControlAPIDataContractsHoliday Distributel holiday.
//
// swagger:model Thinktel.uControl.Api.DataContracts.Holiday
type ThinkteluControlAPIDataContractsHoliday struct {

	// Date of holiday.
	// Required: true
	Date *string `json:"Date"`

	// Name of holiday.
	// Required: true
	Name *string `json:"Name"`
}

// Validate validates this thinktel u control Api data contracts holiday
func (m *ThinkteluControlAPIDataContractsHoliday) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ThinkteluControlAPIDataContractsHoliday) validateDate(formats strfmt.Registry) error {

	if err := validate.Required("Date", "body", m.Date); err != nil {
		return err
	}

	return nil
}

func (m *ThinkteluControlAPIDataContractsHoliday) validateName(formats strfmt.Registry) error {

	if err := validate.Required("Name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this thinktel u control Api data contracts holiday based on context it is used
func (m *ThinkteluControlAPIDataContractsHoliday) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsHoliday) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsHoliday) UnmarshalBinary(b []byte) error {
	var res ThinkteluControlAPIDataContractsHoliday
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
