// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ThinkteluControlAPIDataContractsTicketResponse thinktel u control Api data contracts ticket response
//
// swagger:model Thinktel.uControl.Api.DataContracts.TicketResponse
type ThinkteluControlAPIDataContractsTicketResponse struct {

	// message
	Message string `json:"Message,omitempty"`

	//
	//
	//     Rejected = 0
	//     Accepted = 1
	//     Deferred = 2
	//     Conditional = 3
	//     Error = 4
	//
	// Required: true
	Reply *int64 `json:"Reply"`

	// ticket mask
	// Required: true
	TicketMask *string `json:"TicketMask"`
}

// Validate validates this thinktel u control Api data contracts ticket response
func (m *ThinkteluControlAPIDataContractsTicketResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReply(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTicketMask(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ThinkteluControlAPIDataContractsTicketResponse) validateReply(formats strfmt.Registry) error {

	if err := validate.Required("Reply", "body", m.Reply); err != nil {
		return err
	}

	return nil
}

func (m *ThinkteluControlAPIDataContractsTicketResponse) validateTicketMask(formats strfmt.Registry) error {

	if err := validate.Required("TicketMask", "body", m.TicketMask); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this thinktel u control Api data contracts ticket response based on context it is used
func (m *ThinkteluControlAPIDataContractsTicketResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsTicketResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsTicketResponse) UnmarshalBinary(b []byte) error {
	var res ThinkteluControlAPIDataContractsTicketResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
