// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ThinkteluControlAPIDataContractsSurecallNumber thinktel u control Api data contracts surecall number
//
// swagger:model Thinktel.uControl.Api.DataContracts.SurecallNumber
type ThinkteluControlAPIDataContractsSurecallNumber struct {

	// forward
	// Required: true
	Forward *string `json:"Forward"`

	// number
	// Required: true
	Number *int64 `json:"Number"`
}

// Validate validates this thinktel u control Api data contracts surecall number
func (m *ThinkteluControlAPIDataContractsSurecallNumber) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateForward(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNumber(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ThinkteluControlAPIDataContractsSurecallNumber) validateForward(formats strfmt.Registry) error {

	if err := validate.Required("Forward", "body", m.Forward); err != nil {
		return err
	}

	return nil
}

func (m *ThinkteluControlAPIDataContractsSurecallNumber) validateNumber(formats strfmt.Registry) error {

	if err := validate.Required("Number", "body", m.Number); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this thinktel u control Api data contracts surecall number based on context it is used
func (m *ThinkteluControlAPIDataContractsSurecallNumber) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsSurecallNumber) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsSurecallNumber) UnmarshalBinary(b []byte) error {
	var res ThinkteluControlAPIDataContractsSurecallNumber
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
