// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ThinkteluControlAPIDataContractsResidentialLineOrder thinktel u control Api data contracts residential line order
//
// swagger:model Thinktel.uControl.Api.DataContracts.ResidentialLineOrder
type ThinkteluControlAPIDataContractsResidentialLineOrder struct {

	// account
	// Required: true
	Account *int64 `json:"Account"`

	// call forwarding delay
	CallForwardingDelay int32 `json:"CallForwardingDelay,omitempty"`

	// call forwarding number
	CallForwardingNumber int64 `json:"CallForwardingNumber,omitempty"`

	// caller ID
	CallerID int64 `json:"CallerID,omitempty"`

	// caller name
	CallerName string `json:"CallerName,omitempty"`

	// email
	Email string `json:"Email,omitempty"`

	// enabled
	// Required: true
	Enabled *bool `json:"Enabled"`

	// label
	Label string `json:"Label,omitempty"`

	//
	//
	//     EnglishUS = 0
	//     EnglishUK = 1
	//     EnglishCA = 2
	//     UserDefined1 = 3
	//     UserDefined2 = 4
	//     FrenchCA = 5
	//     SpanishLatinAmerica = 6
	//
	// Required: true
	Locale *int64 `json:"Locale"`

	// number
	// Required: true
	Number *ThinkteluControlAPIDataContractsNumberRequest `json:"Number"`

	// plan ID
	// Required: true
	PlanID *string `json:"PlanID"`

	//
	//
	//     EnglishUS = 0
	//     EnglishUK = 1
	//     EnglishCA = 2
	//     UserDefined1 = 3
	//     UserDefined2 = 4
	//     FrenchCA = 5
	//     SpanishLatinAmerica = 6
	//     None = 9
	//
	// Required: true
	SecondLocale *int64 `json:"SecondLocale"`

	// Sip password
	SIPPassword string `json:"SipPassword,omitempty"`

	// web self care password
	WebSelfCarePassword string `json:"WebSelfCarePassword,omitempty"`
}

// Validate validates this thinktel u control Api data contracts residential line order
func (m *ThinkteluControlAPIDataContractsResidentialLineOrder) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnabled(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLocale(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlanID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecondLocale(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ThinkteluControlAPIDataContractsResidentialLineOrder) validateAccount(formats strfmt.Registry) error {

	if err := validate.Required("Account", "body", m.Account); err != nil {
		return err
	}

	return nil
}

func (m *ThinkteluControlAPIDataContractsResidentialLineOrder) validateEnabled(formats strfmt.Registry) error {

	if err := validate.Required("Enabled", "body", m.Enabled); err != nil {
		return err
	}

	return nil
}

func (m *ThinkteluControlAPIDataContractsResidentialLineOrder) validateLocale(formats strfmt.Registry) error {

	if err := validate.Required("Locale", "body", m.Locale); err != nil {
		return err
	}

	return nil
}

func (m *ThinkteluControlAPIDataContractsResidentialLineOrder) validateNumber(formats strfmt.Registry) error {

	if err := validate.Required("Number", "body", m.Number); err != nil {
		return err
	}

	if m.Number != nil {
		if err := m.Number.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Number")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Number")
			}
			return err
		}
	}

	return nil
}

func (m *ThinkteluControlAPIDataContractsResidentialLineOrder) validatePlanID(formats strfmt.Registry) error {

	if err := validate.Required("PlanID", "body", m.PlanID); err != nil {
		return err
	}

	return nil
}

func (m *ThinkteluControlAPIDataContractsResidentialLineOrder) validateSecondLocale(formats strfmt.Registry) error {

	if err := validate.Required("SecondLocale", "body", m.SecondLocale); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this thinktel u control Api data contracts residential line order based on the context it is used
func (m *ThinkteluControlAPIDataContractsResidentialLineOrder) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateNumber(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ThinkteluControlAPIDataContractsResidentialLineOrder) contextValidateNumber(ctx context.Context, formats strfmt.Registry) error {

	if m.Number != nil {

		if err := m.Number.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Number")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Number")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsResidentialLineOrder) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsResidentialLineOrder) UnmarshalBinary(b []byte) error {
	var res ThinkteluControlAPIDataContractsResidentialLineOrder
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
