// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ThinkteluControlAPIDataContractsDID thinktel u control Api data contracts Did
//
// swagger:model Thinktel.uControl.Api.DataContracts.Did
type ThinkteluControlAPIDataContractsDID struct {

	// additional label
	AdditionalLabel string `json:"AdditionalLabel,omitempty"`

	// label
	Label string `json:"Label,omitempty"`

	// number
	// Required: true
	Number *int64 `json:"Number"`

	// translated number
	TranslatedNumber int64 `json:"TranslatedNumber,omitempty"`

	// unavailable call forwarding
	UnavailableCallForwarding int64 `json:"UnavailableCallForwarding,omitempty"`
}

// Validate validates this thinktel u control Api data contracts Did
func (m *ThinkteluControlAPIDataContractsDID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNumber(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ThinkteluControlAPIDataContractsDID) validateNumber(formats strfmt.Registry) error {

	if err := validate.Required("Number", "body", m.Number); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this thinktel u control Api data contracts Did based on context it is used
func (m *ThinkteluControlAPIDataContractsDID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsDID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThinkteluControlAPIDataContractsDID) UnmarshalBinary(b []byte) error {
	var res ThinkteluControlAPIDataContractsDID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
